# format = mail-header

## Raw data (and opus numbers) from http://home.wanadoo.nl/ovar/schnopus.htm

## <H3>Works</H3>
## In fact Alfred Schnittke didn't use opus numbers.
## Here opus numbers are used to facilitate indexing.<P>

Title-Type: Concerto
Title-For: accordion and orchestra
Title-Opus: 1
Title-Dates: 1949

## <DL><DD>Lost</DL>

Title-Type: Incidental music
Title-Related-How: to
Title-Related-Name: Mayakovsky's Debut
Title-Opus: 2
Title-Dates: 1950-1952

Title-RAW: Poème
Title-For: piano and orchestra
Title-Opus: 3
Title-Dates: 1953

Title-Name: The Passing Line of Clouds Grows Thinner
Title-For: voice and piano
Title-Opus: 4
Title-Dates: 1953

## <DL><DD>To a poem by Alexander Pushkin.</DL>

Title-Type: Fugue
Title-For: violin solo
Title-Opus: 5
Title-Dates: 1953

## <DL><DD><I>CD <A HREF="/ovar/sovrev/kancheli/bis1392.htm">BIS CD 1392</A>: Vadim Gluzman (violin)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/naxos8554728.htm">Naxos 8.554728</A>: Mark Lubotsky (violin)</I></DL>

Title-Count: Six
Title-Type: Preludes
Title-For: piano
Title-Opus: 6
Title-Dates: 1953-1954

Title-Type: Variations
Title-For: piano
Title-Opus: 7
Title-Dates: 1954-1955

Title-Type: Sonata
Title-For: violin and piano
Title-Opus: 8
Title-Dates: 1954-1955

## <DL><DD><I>CD Warner Classics 2564 61329-2: Daniel Hope (violin), Sebastian Knauer (piano)</I></DL>

Title-Name: Dusk (Sumrak)
Title-For: voice and piano
Title-Opus: 9
Title-Dates: 1954-1955

## <DL><DD>To a poem by Fyodor Tyutchev.</DL>

Title-Name: Beggar (Nishchy)
Title-For: voice and piano
Title-Opus: 10
Title-Dates: 1954-1955

## <DL><DD>To a poem by Mikhail Lermontov.</DL>

Title-Name: Birch Tree (Beryozka)
Title-For: voice and piano
Title-Opus: 11
Title-Dates: 1954-1955

## <DL><DD>To a poem by Stepan Shchiparev.</DL>

Title-Count: Three
Title-Type: Choruses
Title-For: mixed chorus
Title-Opus: 12
Title-Dates: 1954/1955

## <DL><DD>To a poems by Alexander Prokofiev, Mikhail Isakovsky and Alexander Mashistov.<P>
## <I>CD Delos DE 3264: The Spiritual Revival Choir of Moscow's Schnittke Institute of Music, Lev Kontorovich (cond)</I></DL>

Title-Type: Scherzo
Title-For: piano quintet
Title-Opus: 13
Title-Dates: 1954-1955

Title-Type: Intermezzo
Title-For: piano quintet
Title-Opus: 14
Title-Dates: 1954-1955

Title-Type: Suite
Title-For: strings
Title-Opus: 15
Title-Dates: 1954-1955

Title-Type: Overture
Title-For: orchestra
Title-Opus: 16
Title-Dates: 1954-1955

Title-Type: Symphony
Title-No: 0
Title-Opus: 17
Title-Dates: 1956-1957

Title-Type: Concerto
Title-No: 1
Title-For: violin and orchestra
Title-Opus: 18
Title-Dates: 1957

## <DL><DD>Revised in 1962.<BR>
## In four movements:<BR>
## 1. Allegro ma non troppo. Tempo iniziale - 13 min.<BR>
## 2. Presto (This movement may be omitted) - 5 min.<BR>
## 3. Andante - 10 min.<BR>
## 4. Allegro scherzando - 9 min.<P>
## <I>CD BIS CD 487: Malmö SO, Eri Klas (cond), Mark Lubotsky (violin)</I></DL>

Title-Name: Nagasaki
Title-Type-After-Name: oratorio
Title-For: mezzo-soprano, mixed chorus and symphony orchestra
Title-Opus: 19
Title-Dates: 1958

## <DL><DD>On a text by Anatoly Sofronov, Georgi Fere, Eneda Eisaku and Simedziku Toson.<BR>
## In five movements:<BR>
## 1. Nagasaki: city of grief<BR>
## 2. Morning (attacca)<BR>
## 3. That fateful day ...<BR>
## 4. After the holocaust<BR>
## 5. The sun of peace</DL>

Title-Name: Vocalise
Title-For: mixed chorus a cappella
Title-Opus: 20
Title-Dates: 1958

Title-RAW: Songs of War and Peace, cantata
Title-For: soprano, mixed chorus and symphony orchestra
Title-Opus: 21
Title-Dates: 1959

## <DL><DD>On texts by Anatoly Leontyev and Andrei Pokrovsky, based on modern Russian folk songs.<BR>
## In four movements:<BR>
## 1. Golden grass on ancient burial mounds<BR>
## 2. War is rumbling in the fields<BR>
## 3. My heart moans<BR>
## 4. The storm has passed. The sky is clear</DL>

Title-Type: String Quartet
Title-Opus: 22
Title-Dates: 1959

## <DL><DD>Unfinished.</DL>

Title-Type: Concerto
Title-For: piano and orchestra
Title-Opus: 23
Title-Dates: 1960

## <DL><DD>1. Allegro<BR>
## 2. Andante (attacca)<BR>
## 3. Allegro</DL>

Title-Type: Concerto
Title-For: electric instruments
Title-Opus: 24
Title-Dates: 1960

## <DL><DD>Unfinished.</DL>

Title-RAW: Poem about Cosmos
Title-For: orchestra
Title-Opus: 25
Title-Dates: 1961

Title-Name: The Eleventh Commandment
Title-Type-After-Name: opera in two acts
Title-Opus: 26
Title-Dates: 1962

## <DL><DD>Libretto by Marina Churova, Georgy Ansimov and Alfred Schnittke.</DL>

Title-RAW: Children's Suite
Title-For: small orchestra
Title-Opus: 27
Title-Dates: 1962

## <DL><DD>In six movements:<BR>
## 1. Moderato<BR>
## 2. Vivo<BR>
## 3. Moderato<BR>
## 4. Andantino<BR>
## 5. Allegro<BR>
## 6. Andantino</DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Introduction
Title-Opus: 28
Title-Dates: 1962

Title-Type: Music
Title-Related-How: to the TV-production
Title-Related-Name: The Rose and the Cross
Title-Opus: 29
Title-Dates: 1962

## <DL><DD>After Alexander Blok</DL>

Title-Type: Sonata
Title-No: 1
Title-For: violin and piano
Title-Opus: 30
Title-Dates: 1963

## <DL><DD>In three movements:<BR>
## 1. Andante - 3 min.<BR>
## 2. Allegretto - 6 min.<BR>
## 3. Largo - 5 min.<BR>
## 4. Allegretto scherzando. Largo - 6 min.<P>
## <I>LP Chandos ABRD 1089: Rostislav Dubinsky (violin), Ljuba Edlina (piano)<BR>
## CD ASV CDDCA 868: Mateja Marinkovic (violin), Linn Hendry (piano)<BR>
## CD BIS CD 364: Christian Bergqvist (violin), Roland Pontinen (piano)<BR>
## CD BIS CD 527: U. Wallin (violin), Roland Pöntinen (piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/bridge9104.htm">Bridge 9104</A>: Joanna Kurkowicz (violin), Sergey Schepkin (piano)<BR>
## CD Catalyst 09026-62668-2: Maria Bachmann (violin), Jon Klibonoff (piano)<BR>
## CD Chandos CHAN 8343: Rostislav Dubinsky (violin), Ljuba Edlina (piano)<BR>
## CD Duchesne CD 71 532: I. Tseitlin (violin), P. Dheur (piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/hmn911701.htm">Harmonia Mundi HMN 911701</A>: Graf Mourja (violin), Elena Rozanova(piano)<BR>
## CD Live Classics LCL 191: Oleg Kagan (violin), Vassily Lobanov (piano)<BR>
## CD Ondine ODE 800-2: Mark Lubotsky (violin), Ralf Gothoni (piano)<BR>
## CD Ondine ODE 901-2: Pekka Kuusisto (violin), Raija Kerppo (piano)<BR>
## CD Proud Sound PROU CD 139: Rusne Mataityte (violin), Margrit-Julia Zimmermann (piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/sp22579.htm">Sonora Products SO 22579 CD</A>: Valery Gradow (violin), Inna Heifitz (piano)<BR>
## CD Stradivarius STR 33675: Francesco D'Orazio (violin), Giampaolo Nuti (piano)<BR>
## CD Vienna Modern Masters VMM 2025: Vasilij Meljnikov (violin), Aljoscha Starc (piano)</I></DL>

Title-RAW: Prelude and Fugue
Title-For: piano
Title-Opus: 31
Title-Dates: 1963

## <DL><DD>1. Andante<BR>
## 2. Allegretto<P>
## <I>CD Chandos CHAN 9704: Boris Berman (piano)</I></DL>

Title-Type: Incidental music
Title-Related-How: to
Title-Related-Name: Caesar and Cleopatra
Title-Opus: 32
Title-Dates: 1963

## <DL><DD>Play in five acts by George Bernard Shaw.</DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Aim the Barrage at Us
Title-Opus: 33
Title-Dates: 1963-1964

Title-Type: Music
Title-For: piano and chamberorchestra
Title-Opus: 34
Title-Dates: 1964

## <DL><DD>In four movements:<BR>
## 1. Variazioni<BR>
## 2. Cantus firmus<BR>
## 3. Cadenza (attacca)<BR>
## 4. Basso ostinato<P>
## <I>CD Chandos CHAN 9466: Russian State SO, Gennadi Rozhdestvensky (cond), Vassily Lobanov, Vassily (piano)</I></DL>

Title-Type: Music
Title-For: chamberorchestra
Title-Opus: 35
Title-Dates: 1964

Title-RAW: Three Verses of Marina Tsvetayeva
Title-For: mezzo-soprano (or soprano) and piano
Title-Opus: 36
Title-Dates: 1965

Title-Type: Dialogue
Title-For: cello and seven instrumentalists
Title-Opus: 37
Title-Dates: 1965

## <DL><DD>Duration: 12 minutes.<P>
## <I>CD BIS CD 568: (Arrangement for trombone by Ch. Lindberg and A. Schnittke) Tapiola Sinfonietta, Osmo Vänskä (cond), Christian Lindberg (trombone)<BR>
## CD BIS CD 568: (Arrangement for trombone by Ch. Lindberg and A. Schnittke) Tapiola Sinfonietta, Osmo Vänskä (cond), Christian Lindberg (trombone)<BR>
## CD Live Classics LCL 202: Gnessin Chamber Orchestra, Yuri Nikolaevsky (cond), Natalia Gutman (cello)</I></DL>

Title-RAW: Improvisation and Fugue
Title-For: piano
Title-Opus: 38
Title-Dates: 1965

## <DL><DD>1. Lento<BR>
## 2. Vivo<P>
## <I>CD Chandos CHAN 9704: Boris Berman (piano)</I></DL>

Title-RAW: Variations on One Chord
Title-For: piano
Title-Opus: 39
Title-Dates: 1965

## <DL><DD>Grave / Lento / Allegretto / Andante / Agitato / Lento / Maestoso / Andante<P>
## <I>CD Chandos CHAN 9704: Boris Berman (piano)</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Adventures of a Dentist
Title-Opus: 40
Title-Dates: 1965

Title-RAW: Charleston
Title-For: stage orchestra/jazz ensemble
Title-Related-How: from the Film
Title-Related-Name: The Adventures of a Dentist
Title-Opus: 40a
Title-Dates: 1965

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Concealed Caballero
Title-Opus: 41
Title-Dates: 1965

Title-Type: Concerto
Title-No: 2
Title-For: violin and chamber orchestra
Title-In-Movements: in a single movement
Title-Opus: 42
Title-Dates: 1966

## <DL><DD>Dedicated to Mark Lubotsky.
## Duration: 23 minutes.<P>
## <I>LP Philips 411 107-1: Basle Symphony Orchestra, Heinz Holliger (cond), Gidon Kremer (violin)<BR>
## CD BIS CD 487: Malmö SO, Eri Klas (cond), Mark Lubotsky (violin)<BR>
## CD Teldec 4509-94540-2: Chamber Orchestra of Europe, Gidon Kremer (violin)</I></DL>

Title-Type: String Quartet
Title-No: 1
Title-Opus: 43
Title-Dates: 1966

## <DL><DD>Commissioned by Rostislav Dubinsky, Primarius of the Borodin Quartet.<BR>
## In three movements:<BR>
## 1. Sonata - 8 min.<BR>
## 2. Canon - 4 min.<BR>
## 3. Cadenza - 7 min.<P>
## <I>CD <A HREF="/ovar/sovrev/schnittke/arco54.htm">Arco Diva UP 0054-2 131</A>: Kapralova Quartet<BR>
## CD BIS CD 467: Tale Quartet<BR>
## CD Nonesuch 79500-2: Kronos Quartet</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Just a Little Joke
Title-Opus: 44
Title-Dates: 1966

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Day Stars
Title-Opus: 45
Title-Dates: 1966

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Commissar
Title-Opus: 46
Title-Dates: 1967

## <DL><DD><I>CD <A HREF="/ovar/sovrev/schnittke/cap71041.htm">Capriccio hybrid CD/SACD CC 71041</A>: Berlin Radio Symphony Orchestra, Frank Strobel (cond)</I></DL>

Title-Name: Pianissimo
Title-For: large symphony orchestra
Title-Opus: 47
Title-Dates: 1968

## <DL><DD>Duration: 9 minutes.<P>
## <I>CD BIS CD 427: Gothenburg SO, Neeme Jarvi (cond)</I></DL>

Title-Type: Serenada
Title-For: violin, clarinet, double-bass, piano and percussion
Title-Opus: 48
Title-Dates: 1968

## <DL><DD>1. -<BR>
## 2. Lento<BR>
## 3. Allegretto<P>
## <I>CD Hyperion CDA 66885: Capricorn, Timothy Mason (cond)</I></DL>

Title-Type: Sonata
Title-No: 2
Title-For: violin and piano
Title-Name: Quasi una sonata
Title-In-Movements: in a single movement
Title-Opus: 49
Title-Dates: 1968

## <DL><DD>Dedicated to Mark Lubotsky and Lyubov Yedlina.<P>
## <I>CD ASV CDDCA 868: Mateja Marinkovic (violin), Linn Hendry (piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/bridge9104.htm">Bridge 9104</A>: Joanna Kurkowicz (violin), Sergey Schepkin (piano)<BR>
## CD Duchesne CD 71 532: I. Tseitlin (violin), P. Dheur (piano)<BR>
## CD Northern Flowers NF 9908: Lidia Kovalenko (violin), Yuri Serov (piano)<BR>
## CD Ondine ODE 800-2: Mark Lubotsky (violin), Ralf Gothoni (piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/phoenix150.htm">Phoenix PHCD 150</A>: Levon Ambartsumian (violin), Anatoly Sheludyakov (piano)<BR>
## CD Russian Disc RDCD 10001: Levon Ambartsumian (violin), Anatoly Sheludyakov (piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/sp22579.htm">Sonora Products SO 22579 CD</A>: Valery Gradow (violin), Inna Heifitz (piano)<BR>
## CD Stradivarius STR 33675: Francesco D'Orazio (violin), Giampaolo Nuti (piano)</I></DL>

Title-Type: Sonata
Title-For: violin and chamber orchestra
Title-Opus: 50
Title-Dates: 1968

## <DL><DD>Arrangement of Violin Sonata no. 1 (1963).<BR>
## 1. Andante - 3 min.<BR>
## 2. Allegretto - 5 min. 30 sec.<BR>
## 3. Largo - 5 min. 30 sec.<BR>
## 4. Allegretto scherzando. Allegro - 5 min. 30 sec.<P>
## <I>CD BIS CD 537: Stockholm Chamber Orchestra, Lev Markiz (cond), Christian Bergqvist (violin)<BR>
## CD Capriccio 67 016: Moscow Virtuosi, V. Spivakov (cond)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/chan9891.htm">Chandos CHAN 9891</A>: Musici de Montreal, Yuli Turovsky (conductor), Stepan Arman (violin)<BR>
## CD Nimbus NI 5582: English SO, William Boughton (cond), Daniel Hope (violin)</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Angel
Title-Opus: 51
Title-Dates: 1968

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: July the Sixth
Title-Opus: 52
Title-Dates: 1968

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Day Stars
Title-Opus: 53
Title-Dates: 1968

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Ownerlewss House
Title-Opus: 54
Title-Dates: 1968

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Glass Harmonica
Title-Opus: 55
Title-Dates: 1968

## <DL><DD><I>CD <A HREF="/ovar/sovrev/schnittke/cap71061.htm">Capriccio 71061</A> (SACD): Rundfunk-Sinfonieorchester Berlin, Frank Strobel (cond)</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Used Cartridge Cases
Title-Opus: 56
Title-Dates: 1968

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Night Call
Title-Opus: 57
Title-Dates: 1968

Title-RAW: Magdalena's Song for voice and piano on words by Boris Pasternak
Title-Opus: 58
Title-Dates: 1968

Title-RAW: "Potok" ("Stream"), electronic composition
Title-Opus: 59
Title-Dates: 1969

## <DL><DD><I>Melodiya C 30721</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Waltz
Title-Opus: 60
Title-Dates: 1969

## <DL><DD><I>CD <A HREF="/ovar/sovrev/schnittke/cap71061.htm">Capriccio 71061</A> (SACD): Rundfunk-Sinfonieorchester Berlin, Frank Strobel (cond)</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Sick at Heart
Title-Opus: 61
Title-Dates: 1969

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: A Ballerina Aboard
Title-Opus: 62
Title-Dates: 1969

Title-RAW: Incidental music to Alexander Pushkin's poem
Title-Name: Boris Godunov
Title-Opus: 63
Title-Dates: 1969

Title-Type: Concerto
Title-For: oboe, harp and string orchestra
Title-In-Movements: in a single movement
Title-Opus: 64
Title-Dates: 1971

## <DL><DD>Dedicated to Heinz Holliger, Ursula Holliger and the Zagreb Soloists Chamber Orchestra.<BR>
## Lento (one movement)<BR>
## Duration: 17 minutes.<P>
## <I>CD BIS CD 377: New Stockholm Chamber Orchestra, Lev Markiz (cond), Helen Jahren (oboe), Kjell Axel Lier (harp)</I></DL>

Title-RAW: Canon in Memoriam Igor Strawinsky
Title-For: string quartet
Title-Opus: 65
Title-Dates: 1971

## <DL><DD>Commissioned by the music magazine 'Tempo', London.<BR>
## Lento (one movement).<BR>
## Duration: 4 minutes 30 seconds.<P>
## <I>CD BIS CD 547: Tale Quartet<BR>
## CD DG 431 686-2: Hagen Quartet<BR>
## CD Etcetera KTC 1124: Mondriaan Quartet<BR>
## CD Nonesuch 79500-2: Kronos Quartet<BR>
## CD RCA-BMG Catalyst 82876 64283-2: Chilingirian Quartet: Levon Chilingirian (violin), Charles Sewart (violin), Simon Rowland-Jones (viola), Philip De Groote (cello)</I></DL>

Title-Count: Eight
Title-Type: Pieces
Title-For: piano
Title-Opus: 66
Title-Dates: 1971

## <DL><DD>1. Folk Song Andantino<BR>
## 2. In the Mountains Moderato<BR>
## 3. Cuckoo and Woodpecker Vivo<BR>
## 4. Melody Andante<BR>
## 5. Tale Lento<BR>
## 6. Play Allegro<BR>
## 7. Children's Piece Andantino<BR>
## 8. March Allegretto<P>
## <I>CD Chandos CHAN 9704: (Four Pieces) Boris Berman (piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/mv06.htm">MV Productions SPPS CD06</A>: Svetlana Ponomarëva (piano)</I></DL>

Title-Name: Labyrinths
Title-Type-After-Name: ballet
Title-In-Movements: in five episodes
Title-Opus: 67
Title-Dates: 1971

## <DL><DD>1. Moderato. Allegretto. Meno mosso. Adagio - 12 min. 30 sec.<BR> 
## 2. Moderato - 3 min. 30 sec.<BR>
## 3. Allegretto - 2 min.<BR>
## 4. Agitato - 4 min.<BR> 
## 5. Cadenza. Andante. Maestoso - 16 min.<P>
## <I>CD BIS CD 557: Malmö SO Chamber Ensemble, Lev Markiz (cond)</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Belorussian Station
Title-Opus: 68
Title-Dates: 1971

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Uncle Vanya
Title-Opus: 69
Title-Dates: 1971

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Sport, Sport, Sport
Title-Opus: 70
Title-Dates: 1971

## <DL><DD><I>CD <A HREF="/ovar/sovrev/schnittke/ocd606.htm">Olympia OCD 606</A>: USSR Cinematography SO, Emin Khachaturian (cond)</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Seagull
Title-Opus: 71
Title-Dates: 1971

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Our Gagarin
Title-Opus: 72
Title-Dates: 1971

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Last Flight of the Albatross
Title-Opus: 73
Title-Dates: 1971

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: You and Me
Title-Opus: 74
Title-Dates: 1971

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: A Cottage in Kolomna
Title-Opus: 75
Title-Dates: 1971

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Wardrobe
Title-Opus: 76
Title-Dates: 1971

Title-Name: Verses Written in the Sleeplessness of the Night
Title-For: voice and piano
Title-Opus: 77
Title-Dates: 1971

## <DL><DD>On verses by Alexander Pushkin.<BR>
## Originally composed for a television production.</DL>

Title-Type: Symphony
Title-No: 1
Title-Opus: 78
Title-Dates: 1969-1972

## <DL><DD>In four movements:<BR>
## 1. Senza tempo / Moderato / Allegro / Andante - 21 min.<BR>
## 2. Allegretto - 15 min.<BR>
## 3. Lento (attacca) - 9 min.<BR>
## 4. Lento - 27 min.<P>
## <I>CD BIS CD 577: Royal Stockholm PO, Leif Segerstam (cond), Ben Kallenberg (violin), Ake Lannerholm (trombone), Carl-Axel Dominique (piano)<BR>
## CD Chandos CHAN 9417: Russian State SO, Gennadi Rozhdestvensky (cond)<BR>
## CD Melodiya SUCD 10 00062: USSR Ministry of Culture SO, Gennadi Rozhdestvensky (cond)</I></DL>

Title-RAW: "Voices of Nature" (without text)
Title-For: ten female voices and vibraphone
Title-Opus: 79
Title-Dates: 1972

## <DL><DD>Lento (one movement).<BR>
## Duration: 5 minutes.<P>
## <I>CD <A HREF="/ovar/sovrev/schnittke/bis1157.htm">BIS 1157</A>: Swedish Radio Choir, Tonu Kaljuste (cond), Jonny Ronnlund (vibraphone)<BR>
## CD Chandos CHAN 9480: Danish National Radio Choir, Stefan Parkman (cond), Gert Sorensen (vibraphone)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/cda67297.htm">Hyperion CDA 67297</A>: Holst Singers, Stephen Layton (cond)</I></DL>

Title-RAW: Suite in Old Style
Title-For: violin and piano (or harpsichord)
Title-Opus: 80
Title-Dates: 1972

## <DL><DD>In five movements:<BR>
## 1.Pastorale - 4 min.<BR>
## 2. Ballet - 2 min.<BR>
## 3. Minuet - 4 min.<BR>
## 4. Fugue - 2 min. 30 sec.<BR>
## 5. Pantomime - 3 min. 30 sec.<P>
## <I>LP Chandos ABRD 1089: Rostislav Dubinsky (violin), Ljuba Edlina (piano)<BR>
## LP Melodiya C10 20223 005: V. Kafelnikov (trumpet), L. Grabko (piano)<BR>
## LP Melodiya C10 25671 007: E. Grach (violin), A. Maloletkova (piano)<BR>
## CD Arco Diva UP 0077-2: Ivana Tomaskova (violin), Renata Ardasevova (piano)<BR>
## CD ASV CDDCA 877: Mateja Marinkovic (violin), Linn Hendry (piano)<BR>
## CD BIS CD 527: U. Wallin (violin), R. Pöntinen (piano)<BR>
## CD <A HREF="/ovar/sovrev/kancheli/bis1392.htm">BIS CD 1392</A>: Vadim Gluzman (violin), Angela Yoffe (piano)<BR>
## CD Chandos CHAN 8343: Rostislav Dubinsky (violin), Ljuba Edlina (piano)<BR>
## CD Duchesne CD 71 532: I. Tseitlin (violin), P. Dheur (piano)<BR>
## CD Ondine ODE 800-2: Mark Lubotsky (violin), Ralf Gothoni (piano)<BR>
## CD Philips 456-016-2: (Arrangement by Gidon Kremer) Gidon Kremer (violin), Naoko Yoshino (harpsichord)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/sp22579.htm">Sonora Products SO 22579 CD</A>: Valery Gradow (violin), Inna Heifitz (piano)<BR>
## CD Stradivarius STR 33675: Francesco D'Orazio (violin), Giampaolo Nuti (piano)<BR>
## CD Talent DOM 2910 125: Daniel Rubenstein (violin), Muhiddin Dürrüoglu-Demiriz (piano)</I></DL>

Title-RAW: Suite in Old Style
Title-For: cello and piano
Title-Opus: 80a

## <DL><DD>Arranged by Daniel Shafran.<BR>
## In five movements:<BR>
## 1.Pastorale - 4 min.<BR>
## 2. Ballet - 2 min.<BR>
## 3. Minuet - 4 min.<BR>
## 4. Fugue - 2 min. 30 sec.<BR>
## 5. Pantomime - 3 min. 30 sec.<P>
## <I>CD <A HREF="/ovar/sovrev/kancheli/asv4006.htm">ASV Gold GLD 4006</A>: Nikolai Demidenko (cello), Leonid Gorokhov (piano)<BR>
## CD Brilliant Classics 93096 (7 CD-set): Daniel Shafran (cello), Anton Ginzburg (piano)</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Chile in Struggle, Hope and Alarm
Title-Opus: 81
Title-Dates: 1972

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Cheer Up, the Worst is Yet to Come
Title-Opus: 82
Title-Dates: 1972

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Butterfly
Title-Opus: 83
Title-Dates: 1972

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Strange Little Frog
Title-Opus: 84
Title-Dates: 1972

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Where the Arbat crosses Bubulinas Street
Title-Opus: 85
Title-Dates: 1972

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Hot Snow
Title-Opus: 86
Title-Dates: 1972

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Right to Jump
Title-Opus: 87
Title-Dates: 1972

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: In the World of the Fables
Title-Opus: 88
Title-Dates: 1973

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Arduous Roads of Peace/The Balance of Terror
Title-Opus: 89
Title-Dates: 1973

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: My Past and My Thoughts
Title-Opus: 90
Title-Dates: 1973

## <DL><DD><I>CD <A HREF="/ovar/sovrev/schnittke/cpo999796.htm">CPO 999 796-2</A>: Radio SO Berlin, Frank Strobel (cond)</I></DL>

Title-RAW: Gratulationsrondo
Title-Key: C major
Title-For: violin and piano
Title-Opus: 91
Title-Dates: 1973

## <DL><DD>Dedicated to Rostislav Dubinsky on occasion of his 50th birthday.<BR>
## Allegro (one movement).<BR>
## Duration: 10 minutes.<P>
## <I>CD ASV CDDCA 877: Mateja Marinkovic (violin), Linn Hendry (piano)<BR>
## CD BIS CD 527: U. Wallin (violin), R. Pöntinen (piano)<BR>
## CD Northern Flowers NF 9908: Lidia Kovalenko (violin), Yuri Serov (piano)<BR>
## CD Stradivarius STR 33675: Francesco D'Orazio (violin), Giampaolo Nuti (piano)<BR>
## CD Teldec 4509-94540-2: Gidon Kremer (violin), Christoph Eschenbach (piano)</I></DL>

Title-Type: Incidental music
Title-Related-How: to Bertold Brecht's play
Title-Related-Name: Turandot
Title-Opus: 92
Title-Dates: 1973

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The World Today/And Yet I Believe
Title-Opus: 93
Title-Dates: 1972-1974

Title-RAW: "Der Gelbe Klang" ("Yellow Sound"), scenic composition
Title-For: pantomime, instrumental ensemble and tape (mixed chorus)
Title-Opus: 94
Title-Dates: 1973-1974

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Agony of Death
Title-Opus: 95
Title-Dates: 1973-1974

## <DL><DD><I>CD <A HREF="/ovar/sovrev/schnittke/cpo999796.htm">CPO 999 796-2</A>: Radio SO Berlin, Frank Strobel (cond)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/ocd606.htm">Olympia OCD 606</A>: USSR Cinematography SO, Emin Khachaturian (cond)</I></DL>

Title-RAW: Hymn I
Title-For: cello, harp and timpani
Title-Opus: 96
Title-Dates: 1974

## <DL><DD>Duration: 11 minutes.<P>
## <I>LP Melodiya C10 28753 008: A. Ivashkin (cello), I. Pashinskaya (harp), V. Grishin (percussion)<BR>
## CD BIS CD 507: Torleif Thédéen (cello), Ingegerd Fredlund (harp), Anders Holdar (percussion)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/bis300507.htm">BIS CD 300507</A>: Torleif Thédéen (cello), Ingegerd Fredlund (harp), Anders Holdar (percussion)<BR>
## CD Melodiya SUCD 10 00061: A. Ivashkin (cello), I. Pashinskaya (harp), V. Grishin (percussion)</I></DL>

Title-RAW: Hymn II
Title-For: cello and double-bass
Title-Opus: 97
Title-Dates: 1974

## <DL><DD>Duration: 6 minutes.<P>
## <I>LP Melodiya C10 28753 008: A. Ivashkin (cello), V. Bartsalkin (double-bass)<BR>
## CD BIS CD 507: Torleif Thédéen (cello), Entcho Radoukanov (double-bass)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/bis300507.htm">BIS CD 300507</A>: Torleif Thédéen (cello), Entcho Radoukanov (double-bass)<BR>
## CD Melodiya SUCD 10 00061: A. Ivashkin (cello), V. Bartsalkin (double-bass)</I></DL>

Title-RAW: Hymn III
Title-For: cello, bassoon, harpsichord and bells or timpani
Title-Opus: 98
Title-Dates: 1974

## <DL><DD>Duration: 5 minutes.<P>
## <I>LP Melodiya C10 28753 008: A. Ivashkin (cello), Y. Rudometkin (bassoon), V. Chasovennaya (harpsichord), V. Grishin (bells)<BR>
## CD BIS CD 507: Torleif Thédéen (cello), Christian Davidsson (bassoon), Mayumi Kamata (harpsichord), Anders Loguin (percussion)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/bis300507.htm">BIS CD 300507</A>: Torleif Thédéen (cello), Christian Davidsson (bassoon), Mayumi Kamata (harpsichord), Anders Loguin (percussion)<BR>
## CD Melodiya SUCD 10 00061: A. Ivashkin (cello), Y. Rudometkin (bassoon), V. Chasovennaya (harpsichord), V. Grishin (bells)</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Cities and Years
Title-Opus: 99
Title-Dates: 1974

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Captain's Daughter
Title-Opus: 100
Title-Dates: 1974

Title-RAW: Requiem, music to Schiller's Drama
Title-Name: Don Carlos
Title-For: soloists, mixed chorus and instrumental ensemble
Title-Opus: 101
Title-Dates: 1975

## <DL><DD>In fourteen movements<BR>
## 1. Requiem - 3 min. 30 sec.<BR>
## 2. Kyrie - 2 min.<BR>
## 3. Dies irae - 1 min.<BR>
## 4. Tuba mirum - 4 min.<BR>
## 5. Rex tremendae majestatis - 1 min.<BR>
## 6. Recordare - 2 min. 30 sec.<BR>
## 7. Lacrimosa - 2 min. 30 sec.<BR>
## 8. Domine Jesu - 1 min. 30 sec.<BR>
## 9. Hostias - 1 min.<BR>
## 10. Sanctus - 4 min.<BR>
## 11. Benedictus - 2 min.<BR>
## 12. Agnus Dei - 2 min.<BR>
## 13. Credo - 4 min.<BR>
## 14. Requiem - 3 min. 30 sec.<P>
## <I>CD BIS CD 497: Stockholm Sinfonietta, Uppsala Academic Chamber Choir, Stefan Parkman (cond), Kristina Hjartsjo Salomonsson, Ingela Hogeras Sjoberg & Lisbeth Lindholm (soprano), Annika Finnila Eker (contralto), Nils Hogman (tenor)<BR>
## CD CHAN 9564: Russian State Symphony Orchestra, Russian State Symphonic Capella, Valery Polyansky (cond), Olga Sizova (soprano), Anaida Agadzhanian (soprano), Olga Tal (soprano), Tatiana Sharova (soprano), Ludmilla Kuznetsova (mezzo-soprano), Vsevolod Grivnov (tenor)<BR>
## CD Panton 81 1374-221: Prague Symphony Orchestra, Kuhn Mixed Chorus, Jiri Belohlavek (cond), Zdena Kloubova (soprano)</I></DL>

Title-Name: Pantomime
Title-Type-After-Name: suite
Title-For: chamber orchestra
Title-Opus: 102
Title-Dates: 1975

## <DL><DD>After W.A. Mozart's Fragment KV 416d.<BR>
## 1. Pantalone and Colombine<BR>
## 2. The Dottore<BR>
## 3. Pierrot<BR>
## 4. The Turk<BR>
## 5. Pierrot chasing Harlekin<BR>
## 6. Harlekin's Death<BR>
## 7. Pierrot is terrified<BR>
## 8. Finale</DL>

Title-Name: Cantus Perpetuus
Title-For: keyboard instrument and percussion
Title-Opus: 103
Title-Dates: 1975

Title-RAW: Preludium in Memoriam Dmitri Shostakovich
Title-For: two violins (or solo violin and magnetic tape)
Title-Opus: 104
Title-Dates: 1975

## <DL><DD>Andante (one movement).<BR>
## Duration: 5 minutes.<P>
## <I>LP HMV-Melodiya ASD 3547: Gidon Kremer (violin)<BR>
## CD ASV CDDCA 877: Mateja Marinkovic & Thomas Bowes (violin)<BR>
## CD Aurophon AU 31899<BR>
## CD BIS CD 697: Oleg Krysa & Alexander Fischer (violin)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/bridge9104.htm">Bridge 9104</A>: Joanna Kurkowicz (violin), Sergey Schepkin (piano)<BR>
## CD Capriccio 67 115: V. Spivakov (violin)<BR>
## CD Col legno 0647 287: V. Spivakov (violin)<BR>
## CD DG 449 966-2: Gidon Kremer (violin)<BR>
## CD Duchesne CD 71 532: I. Tseitlin & P. Dheur (violin)<BR>
## CD RCA Victor 74321-24894-2: Sasha Rozhdestvensky & Vladimir Spivakov (violin)</I></DL>

Title-RAW: Cadenza to Mozarts Piano Concerto in C minor KV 491 (first movement)
Title-Opus: 105
Title-Dates: 1975

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Autumn
Title-Opus: 106
Title-Dates: 1975

Title-RAW: Eight Songs from the incidental music to Schiller's
Title-Name: Don Carlos
Title-For: voice and piano or guitar
Title-Opus: 107
Title-Dates: 1975

## <DL><DD>1. Prelude<BR>
## 2. Hope<BR>
## 3. A Path in the Mountains<BR>
## 4. Evil Monks<BR>
## 5. Love Song<BR>
## 6. Abouth Theatre<BR>
## 7. To my Friends<BR>
## 8. Song of the Marauders</DL>

Title-Type: Piano Quintet
Title-Opus: 108
Title-Dates: 1972-1976

## <DL><DD>In five movements:<BR>
## 1. Moderato (attacca) - 6 min.<BR>
## 2. Tempo di Valse - 5 min.<BR>
## 3. Andante - 6 min.<BR>
## 4. Lento (attacca) - 5 min.<BR>
## 5. Moderato pastorale - 3 min. 30 sec.<P>
## <I>LP Philips 411 107-1: Gidon Kremer (violin), Kathrin Rabus (violin), Gerard Causse (viola), Ko Iwasaki (cello), Elena Bashkirova (piano)<BR>
## CD Arabesque Z 6707: Lark Quartet, Gary Graffman (piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/asv6251.htm">ASV Quicksilva CD QS 6251</A>: Barbican Piano Trio, Jan Peter Schmolck (violin), James Boyd (viola)<BR>
## CD BIS CD 547: Tale Quartet, Roland Pöntinen (piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/bbm1093.htm">Black Box BBM 1093</A>: Barbican Piano Trio, Jan Peter Schmolck (violin), James Boyd (viola)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/ecm1755.htm">ECM New Series 1755 (461 815-2)</A>: Keller Quartet, Alexei Lubimov (piano)<BR>
## CD Etcetera KTC 1124: Mondriaan Quartet, Fred Oldenburg (piano)<BR>
## CD Hyperion CDA 66885: Capricorn, Timothy Mason (cond)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/naxos8554728.htm">Naxos 8.554728</A>: Mark Lubotsky & Dimity Hall (violin), Theodore Kuchar & Irini Morozova (viola), Alexander Ivashkin & Julian Smiles(cello), Irina Schnittke (piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/naxos8554830.htm">Naxos 8.554830</A>: Vermeer Quartet, Boris Berman (piano)<BR>
## CD Northern Flowers NF 9908: Lidia Kovalenko & Alexey Baev (violin), Alexey Popov (viola), Kirill Timofeev (cello), Yuri Serov (piano)<BR>
## CD Russian Disc RDCD 10 031: Moscow String Quartet, Constantine Orbelian (piano)<BR>
## CD Virgin Classics VC 7 91436-2: Borodin Quartet, Ludmilla Berlinsky (piano)<BR>
## CD <A HREF="/ovar/shosrev/naxos8554830.htm">Naxos 8.554830</A>: Vermeer Quartet, B. Berman (piano)</I></DL>

Title-RAW: "Der Sonnengesang des Franz von Assisi" for two mixed choruses and six instrumentalists
Title-Opus: 109
Title-Dates: 1976

## <DL><DD><I>LP Melodiya: USSR State Chamber Chorus, Ensemble of Bolshoi Theatre Soloists, Valery Polyansky (cond)</I></DL>

Title-RAW: Transcription of Shostakovich's Preludes nos. 1 & 2 (from "Five preludes")
Title-For: small orchestra
Title-Opus: 110
Title-Dates: 1976

Title-RAW: Moz-Art for two violins, after Mozart KV 416
Title-Opus: 111
Title-Dates: 1976

## <DL><DD>Allegretto / Allegro (one movement)><BR>
## Duration: 5 minutes 30 seconds.<P>
## <I>CD BIS CD 697: Oleg Krysa & Alexander Fischer (violin)</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Selecting a Target
Title-Opus: 112
Title-Dates: 1976

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Legend on How Tsar Peter Got the Negro Married
Title-Opus: 113
Title-Dates: 1976

Title-Count: Two
Title-Type: Fragments
Title-For: small symphony orchestra
Title-Related-How: from the music to the film
Title-Related-Name: The Tale of Tsar Peter
Title-Opus: 113a
Title-Dates: 1976

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Lion-Trainers
Title-Opus: 114
Title-Dates: 1976

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Clowns and Kids
Title-Opus: 115
Title-Dates: 1976

## <DL><DD><I>CD <A HREF="/ovar/sovrev/schnittke/cap71061.htm">Capriccio 71061</A> (SACD): Rundfunk-Sinfonieorchester Berlin, Frank Strobel (cond)</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Ricky-Ticky-Tari
Title-Opus: 116
Title-Dates: 1976

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The White Steamer
Title-Opus: 117
Title-Dates: 1976

Title-RAW: Two Cadenzas to Beethoven's Violin Concerto in D major Op. 61
Title-For: solo violin, 10 violins and timpani
Title-Opus: 118
Title-Dates: 1975-1977

Title-Type: Concerto Grosso
Title-No: 1
Title-For: two violins, prepared piano, harpsichord and 21 strings
Title-Opus: 119
Title-Dates: 1977

## <DL><DD>In six movements:<BR>
## 1. Preludio (attacca) - 6 min.<BR>
## 2. Toccata (attacca) - 5 min.<BR>
## 3. Recitativo - 9 min.<BR>
## 4. Cadenza (attacca) - 2 min. 30 sec.<BR>
## 5. Rondò (attacca) - 7 min. 30 sec.<BR>
## 6. Postludio - 3 min.<P>
## <I>CD BIS CD 377: New Stockholm Chamber Orchestra, Lev Markiz (cond), Christian Bergqvist (violin), P. Swedrup (violin), R. Pontinen (piano)<BR>
## CD BIS CD 1507: New Stockholm Chamber Orchestra, Lev Markiz (cond), Christian Bergqvist (violin), P. Swedrup (violin), R. Pontinen (piano)<BR>
## CD Chandos CHAN 9590: I Musici de Montreal, Yuli Turovsky (cond), Natalya Turovsky, Catherine Perrin<BR>
## CD DG 429 413-2: Chamber Orchestra of Europe, Heinrich Schiff (cond), Gidon Kremer (violin), Tatiana Grindenko (violin), Yuri Smirnov (harpsichord and piano)<BR>
## CD DG 439 452-2: Chamber Orchestra of Europe, Heinrich Schiff (cond), Gidon Kremer (violin), Tatiana Grindenko (violin), Yuri Smirnov (harpsichord and piano)<BR>
## CD DG 445 520-2: Chamber Orchestra of Europe, Heinrich Schiff (cond), Gidon Kremer (violin), Tatiana Grindenko (violin), Yuri Smirnov (harpsichord and piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/dg471626.htm">DG 471 626-2</A>: Chamber Orchestra of Europe, Heinrich Schiff (cond), Gidon Kremer (violin), Tatiana Grindenko (violin), Yuri Smirnov (harpsichord and piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/cdman175.htm">Manchester Classical Gallery CDMAN 175</A>: St. Petersburg Mozarteum Chamber Orchestra, Arcady Shteinlukht (cond), Victor Kuleshov (violin), Ilia Ioff (violin), Julia Lev (harpsichord and piano)<BR>
## CD RCA Victor Gold Seal GD 60957: London SO, Gennadi Rozhdestvensky (cond), Gidon Kremer & Tatiana Grindenko (violin)<BR>
## CD RCA Victor 74321-24894-2 (2 CD-set): London SO, Gennadi Rozhdestvensky (cond), Gidon Kremer & Tatiana Grindenko (violin)<BR>
## CD Sikorski SIK 7-003E: London SO, Gennadi Rozhdestvensky (cond), Gidon Kremer & Tatiana Grindenko (violin)</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Human Requitale
Title-Opus: 120
Title-Dates: 1977

Title-RAW: "Magdalina" for voice and piano to a poem by Boris Pasternak
Title-Opus: 121
Title-Dates: 1977

## <DL><DD>Part of Hommage to Zhivago (1993)</DL>

Title-RAW: Moz-Art a la Haydn
Title-For: two violins and eleven strings
Title-Opus: 122
Title-Dates: 1977

## <DL><DD>For 6 violins, 2 violas, 2 cellos and 1 double-bass.<BR>
## Dedicated to Tatyana Grindenko and Gidon Kremer.<P>
## <I>CD ASV CDDCA 877: Mateja Marinkovic & Thomas Bowes (violin)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/bis1437.htm">BIS CD 1437</A>: Tapiola Sinfonietta, Ralf Gothoni (cond), Ulf Wallin & Meri Englund (violin)<BR>
## CD DG 429 413-2: Chamber Orchestra of Europe, Gidon Kremer (cond & violin), Tatiana Grindenko (violin)<BR>
## CD DG 445 520-2: Chamber Orchestra of Europe, Gidon Kremer (cond & violin), Tatiana Grindenko (violin)<BR>
## CD Nonesuch 7559-79633-2: Kremeratica Baltica, Gidon Kremer (violin)</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: My Memories Take Me To You
Title-Opus: 123
Title-Dates: 1977

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Adventures of Travka
Title-Opus: 124
Title-Dates: 1977

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Life-Story of an Unknown Actor
Title-Opus: 125
Title-Dates: 1977

## <DL><DD><I>CD <A HREF="/ovar/sovrev/schnittke/ocd606.htm">Olympia OCD 606</A>: USSR Cinematography SO, Emin Khachaturian (cond)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/cap71041.htm">Capriccio hybrid CD/SACD CC 71041</A>: Berlin Radio Symphony Orchestra, Frank Strobel (cond)</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Ascent
Title-Opus: 126
Title-Dates: 1977

## <DL><DD><I>CD <A HREF="/ovar/sovrev/schnittke/cap71061.htm">Capriccio 71061</A> (SACD): Rundfunk-Sinfonieorchester Berlin, Frank Strobel (cond)</I></DL>

Title-Name: In Memoriam
Title-For: symphony orchestra
Title-Opus: 127
Title-Dates: 1972-1978

## <DL><DD>Orchestral version of the piano quintet<BR>
## 1. Moderato (attacca) - 7 min.<BR>
## 2. Tempo di Valse - 6 min.<BR>
## 3. Andante (attacca) - 7 min.<BR>
## 4. Lento - 4 min. 30 sec.<BR>
## 4. Moderato pastorale - 3 min. 30 sec.<P>
## <I>CD BIS CD 447: Malmö SO, Lev Markiz (cond)<BR>
## CD Chandos CHAN 9466: Russian State Symphony Orchestra, Valery Polyansky (cond)<BR>
## CD Sony Classical CD 48241: London SO, Seiji Ozawa (cond)</I></DL>

Title-Type: Concerto
Title-No: 3
Title-For: violin and chamber orchestra
Title-Opus: 128
Title-Dates: 1978

## <DL><DD>In three movements:<BR>
## 1. Moderato - 10 min.<BR>
## 2. Agitato (attacca) - 6 min.<BR>
## 3. Moderato - 11 min.<P>
## <I>LP Eurodisc 201 234: Berlin Philharmonic Chamber Ensemble, W. Nelson (cond), Gidon Kremer (violin)<BR>
## LP Melodiya C10 15681 000: Soloists Ensemble, Y. Nikolayevsky (cond), Oleg Kagan (violin)
## CD BIS CD 517: Malmö SO, Eri Klas (cond), Oleg Krysa (violin)<BR>
## CD Ondine ODE 893-2: Virtuosi di Kuhmo, Sibelius Academy Wind Players, Ralf Gothoni (cond), Mark Lubotsky (violin)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/phoenix150.htm">Phoenix PHCD 150</A>: Moscow Tchaikovsky SO, Mikhail Kukushkin (cond), Levon Ambartsumian (violin)<BR>
## CD Teldec 4509-94540-2: Chamber Orchestra of Europe, Gidon Kremer (violin)</I></DL>

Title-Type: Sonata
Title-No: 1
Title-For: cello and piano
Title-Opus: 129
Title-Dates: 1978

## <DL><DD>In three movements:<BR>
## 1. Largo (attacca) - 4 min.<BR>
## 2. Presto (attacca) - 7 min.<BR>
## 3. Largo - 12 min.<P>
## <I>CD Aeon AECD 0636: Marc Coppey (cello), Peter Laul (piano)<BR>
## CD BIS CD 336: Torleif Thedéen (cello), Roland Pöntinen (piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/bbm11032.htm">Black Box BBM 1032</A>: Raphael Wallfisch (cello), John York (piano)<BR>
## CD Chandos CHAN 9705: Alexander Ivashkin (cello), Irina Schnittke (piano)<BR>
## CD <A HREF="/ovar/shosrev/cda67534.htm">Hyperion CDA 67534</A>: Alban Gerhardt (cello), Steven Osborne (piano)<BR>
## CD Globe GLO 5041: D. Ferschtmann (cello), M. Baslavskaya (piano)<BR>
## CD Harmonia Mundi HMN 91 1628: Xavier Phillips (cello), Huseyin Sermet (piano)<BR>
## CD Marco Polo 8.223334: Maria Kliegel (cello), Raimund Havenith (piano)<BR>
## CD Melodiya SUCD 10 00088: T. Hugh (cello), C. Tourocque (piano)<BR>
## CD Ode Manu CDMANU 1480: Alexander Ivashkin (cello), Tamas Vesmas (piano)<BR>
## CD <A HREF="/ovar/sovrev/kancheli/qtz2032.htm">Quartz QTZ 2032</A>: Matthew Barley (cello), Stephen De Pledge (piano)<BR>
## CD Thorofon CTH 2459: Sonja Schröder (cello), Peter Martin (piano)<BR>
## CD Unicorn Kanchana DKP CD 9083: Alexander Baillie (cello), Piers Lane (piano)<BR>
## CD United Recordings 88006-2: Paul Marleyn (cello), Sarah Morley (piano)</I></DL>

Title-RAW: "Silent Night" ("Stille Nacht") arranged
Title-For: violin and piano
Title-Opus: 130
Title-Dates: 1978

## <DL><DD>On motives of the like-named German Christmas carol.<BR>
## Lento (one movement).<BR>
## Employing the melody by Franz Xaver Gruber.<BR>
## Duration: 5 minutes<P>
## <I>CD ASV CDDCA 877: Mateja Marinkovic (violin), Linn Hendry (piano)<BR>
## CD BIS CD 527: U. Wallin (violin), Roland Pöntinen (piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/bbm1025.htm">Black Box BBM 1025</A>: Roman Mints (violin), Evgenia Chudinovich(piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/ni5631.htm">Nimbus NI 5631</A>: Daniel Hope (violin), Simon Mulligan (piano)<BR>
## CD Stradivarius STR 33675: Francesco D'Orazio (violin), Giampaolo Nuti (piano)<BR>
## CD Teldec 4509-94540-2: Gidon Kremer (violin), Christoph Eschenbach (piano)</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Father Sergei
Title-Opus: 131
Title-Dates: 1978

Title-Type: Incidental music
Title-Related-How: to Alexander Vampilov's play
Title-Related-Name: A Duck Shooting Party
Title-Opus: 132
Title-Dates: 1978

Title-Type: Incidental music
Title-Related-How: to Nikolai Gogol's play
Title-Related-Name: The Dead Soul Register (The Census List)
Title-Opus: 133
Title-Dates: 1978

## <DL><DD><I>CD <A HREF="/ovar/sovrev/schnittke/chan9885.htm">Chandos CHAN 9885</A>: Russian State SO, Valeri Polyansky (cond), Lev Butenin (reciter)</I></DL>

Title-RAW: Hymn IV
Title-For: cello, bassoon, double-bass, harpsichord, harp, timpani and bells
Title-Opus: 134
Title-Dates: 1974-1979

## <DL><DD>Duration: 3 minutes.<P>
## <I>LP Melodiya C10 28753 008: USSR Bolshoi Theatre Soloists Ensemble, A. Lazarev (cond)<BR>
## CD BIS CD 507: Torleif Thédéen (cello), Christian Davidsson (bassoon), Entcho Radoukanov (double-bass), Mayumi Kamata (harpsichord), Ingegerd Fredlund (harp), Anders Holdar & Anders Loguin (timpani & bells)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/bis300507.htm">BIS CD 300507</A>: Torleif Thédéen (cello), Christian Davidsson (bassoon), Entcho Radoukanov (double-bass), Mayumi Kamata (harpsichord), Ingegerd Fredlund (harp), Anders Holdar & Anders Loguin (timpani & bells)<BR>
## CD Melodiya SUCD 10 00061: USSR Bolshoi Theatre Soloists Ensemble, A. Lazarev (cond)</I></DL>

Title-Type: Symphony
Title-No: 2
Title-Name: St. Florian
Title-For: vocal soloists, chamber choir and symphony orchestra
Title-Opus: 135
Title-Dates: 1979

## <DL><DD>In six movements:<BR>
## 1. Recitativo (Kyrie) - 11 min.<BR>
## 2. Maestoso (Gloria) - 5 min.<BR>
## 3. Moderato (Credo) - 9 min.<BR>
## 4. Pesante (Cucifixus) - 8 min. 30 sec.<BR>
## Coda: Agitato (Et resurrexit), Maestoso - 4 min.<BR>
## Introduction to V. Andante (Sanctus) - 4 min.<BR> 
## 5. Andante (Sanctus. Benedictus) - 8 min.<BR>
## 6. Andante (Agnus Dei) - 11 min.<P>
## <I>LP Melodiya C10 23085 (2 LP-set): Leningrad PO, USSR Ministry of Culture Chamber Chorus, Gennadi Rozhdestvensky (cond)<BR>
## CD BBC Radio Classics 15656-9196-2: BBC Symphony Chorus and Orchestra, BBC Singers, Gennadi Rozhdestvensky (cond), Jean Temperley (contralto),
## Paul Esswood (alto), Neil Jenkins (tenor), Jonathan Robarts (bass)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/bis667.htm">BIS CD 667</A>: Royal Stockholm PO, Mikaeli Chamber Choir, Leif Segerstam (cond), Mikael Bellini (alto),
## Malena Ernman (mezzo-soprano), Goran Eliasson (tenor), Torkel Borelius (bass)<BR>
## CD Chandos CHAN 9519: Russian State Symphonic Cappella and SO, Valery Polyansky (cond),
## Marina Katsman contralto), Yaroslav Zdorov (alto), Oleg Dolgov (tenor), Sergei Veprintsev (bass)<BR>
## CD Melodiya SUCD 10 00063: Leningrad PO, USSR Ministry of Culture Chamber Chorus, Gennadi Rozhdestvensky (cond)</I></DL>

Title-Type: Concerto
Title-For: piano and string orchestra
Title-In-Movements: in a single movement
Title-Opus: 136
Title-Dates: 1979

## <DL><DD>Duration: 21 minutes.<P>
## <I>LP Melodiya C10 22845 004: Lithuanian Chamber Orchestra, S. Sondeckis (cond), V. Krainev (cond)<BR>
## CD BIS CD 377: New Stockholm Chamber Orchestra, Lev Markiz (cond), Roland Pontinen (piano)<BR>
## CD <A HREF="/ovar/shosrev/brioso109.htm">Brioso BR 109</A>: Moscow PO, Vassily Sinaisky (cond), O. Volkov (piano)<BR>
## CD Capriccio 67 016: Moscow Virtuosi, V. Spivakov (cond)<BR>
## CD CHAN 9564: Russian State SO, Valery Polyansky (cond), Igor Khudolei (piano)<BR>
## CD <A HREF="/ovar/shosrev/delos3259.htm">Delos DE 3259</A>: Moscow Chamber Orchestra, Constantine Orbelian (pianist and conductor)<BR>
## CD Erato 2292-45742-2: London Sinfonietta, Gennadi Rozhdestvensky (cond), Victoria Postnikova (piano)<BR>
## CD Koch International Classics 37159-2: Moscow PO, Donald Barra (cond), Israela Margalit (piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/cdman175.htm">Manchester Classical Gallery CDMAN 175</A>: St. Petersburg Mozarteum Chamber Orchestra, Arcady Shteinlukht (cond), Veronica Reznikovskaya (piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/mv06.htm">MV Productions SPPS CD06</A>: Omsk Chamber Orchestra, Yuri Nikolaevsky (cond), Svetlana Ponomarëva (piano)<BR>
## CD Ondine ODE 893-2: Virtuosi di Kuhmo, Ralf Gothoni (cond & piano)<BR>
## CD RCA Victor Red Seal 09026- 60466-2: Moscow Virtuosi, Vladimir Spivakov (cond), Vladimir Krainev (piano)<BR>
## CD RCA Victor 74321-24894-2 (2 CD-set): Moscow Virtuosi, Vladimir Spivakov (cond), Vladimir Krainev (piano)<BR>
## CD Teldec 2292-45742-2: London Sinfonietta, Gennadi Rozhdestvensky (cond), Victoria Postnikova (piano)</I></DL>

Title-RAW: Polyphonic Tango
Title-For: ensemble
Title-Opus: 137
Title-Dates: 1979

## <DL><DD><I>Live Rec: Bolshoi Theatre Soloists Ensemble, A. Lazarev (cond)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/cpo999804.htm">CPO 999 804-2</A>: Radio-Philharmonie Hannover des NDR, Eiji Oue (cond)</I></DL>

Title-RAW: Peaceful Music (Stille Musik)
Title-For: violin and cello
Title-Opus: 138
Title-Dates: 1979

## <DL><DD>Lento (one movement).<BR>
## Duration: 6 minutes.<P>
## <I>CD ASV CDDCA 877: Mateja Marinkovic (violin), Timothy Hugh (cello)<BR>
## CD BIS CD 697: Oleg Krysa (violin), Torleif Thédéen (cello)<BR>
## CD Marco Polo 8.223334: Burkhard Godhoff (violin), Maria Kliegel (cello)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/naxos8554728.htm">Naxos 8.554728</A>: Mark Lubotsky & Dimity Hall (violin), Theodore Kuchar & Irini Morozova (viola), Alexander Ivashkin & Julian Smiles(cello), Irina Schnittke (piano)</I></DL>

Title-RAW: In Memoriam Igor Strawinsky, Sergei Prokofiev and Dmitri Shostakovich
Title-For: piano six hands
Title-Opus: 139
Title-Dates: 1979

## <DL><DD>Based on Chinese March from "The nightingale", Humoresque Scherzo and Polka from "The age of gold".<P>
## <I>Live Rec: Robert Nasveld, Polo de Haas & Nico de Vente (piano)<BR>
## Live Rec: Pianokwadraat (piano)</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Paradoxes of the Evolution
Title-Opus: 140
Title-Dates: 1979

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Fantasies of Faryatyev
Title-Opus: 141
Title-Dates: 1979

Title-Name: Passacaglia
Title-For: large symphony orchestra
Title-Opus: 142
Title-Dates: 1979-1980

## <DL><DD>Duration: 19 minutes.<P>
## <I>CD BIS 437: Malmö SO, Leif Segerstam (cond)</I></DL>

Title-RAW: Gogol Suite
Title-For: orchestra
Title-Related-How: from the spectacle
Title-Related-Name: The Tale of the Inspector
Title-Opus: 143
Title-Dates: 1980

## <DL><DD>Suite from the music to a production of "The Dead Souls Register".<BR>
## Orchestral version by Gennadi Rozhdestvensky.<BR>
## In eight movements:<BR>
## 1. Overture - 1 min.<BR>
## 2. Chichikov's Childhood - 2 min. 30 sec.<BR>
## 3. The Portrait - 7 min.<BR>
## 4. The Overcoat - 2 min. 30 sec.<BR>
## 5. Ferdinand VIII - 1 min. 30 sec.<BR>
## 6. The Bureaucrats - 2 min. 30 sec.<BR>
## 7. The Ball - 6 min. 30 sec.<BR>
## 8. The Legacy - 6 min.<P>
## <I>LP Melodiya C10 18761-62: USSR Ministry of Culture SO, Gennadi Rozhdestvensky (cond)<BR>
## CD BIS CD 557: Malmö SO, Lev Markiz (cond)<BR>
## CD Pope Music PM 1007-2: Russian SO, Mark Gorenstein (cond)</I></DL>

Title-RAW: "The Revisionist's Tale", transcription of five movements of the Gogol Suite
Title-For: two pianos
Title-Opus: 143a

## <DL><DD><I>CD <A HREF="/ovar/sovrev/schnittke/sp22566.htm">Sonora Products SO 22566 CD</A>: Natalia Zusman & Inna Heifetz (pianos)</I></DL>

Title-RAW: Three Madrigals for soprano, violin, viola, double-bass, vibraphone and harpsichord on poems by Francisco Tanzer
Title-Opus: 144
Title-Dates: 1980

## <DL><DD>1. Sur une étoile (Andante)<BR>
## 2. Entfernung (Moderato)<BR>
## 3. Reflection (Andante)<P>
## <I>LP Melodiya C10 18403-4: Bolshoi Theatre Soloists Ensemble, A. Lazarev (cond), N. Lee (soprano)<BR>
## CD Hyperion CDA 66885: Capricorn, , Timothy Mason (cond), Sarah Leonard (soprano)</I></DL>

Title-RAW: Three Scenes for soprano and ensemble without text
Title-Opus: 145
Title-Dates: 1980

## <DL><DD>Dedicated to Mark Pekarski and his ensemble.<BR>
## 1. Poco pesante<BR>
## 2. Moderato<BR>
## 3. Andante</DL>

Title-RAW: Moz-Art, version
Title-For: ensemble
Title-Opus: 146
Title-Dates: 1980

## <DL><DD>For oboe, harp, harpsichord, violin, cello and double bass.<BR>
## Allegretto (one movement)</DL>

Title-Name: Minnesang
Title-For: 52 voices
Title-Opus: 147
Title-Dates: 1980-1981

## <DL><DD>Duration: 19 minutes.<P>
## <I>CD Chandos CHAN 9126: Danish National Radio Choir, Stefan Parkman Cond)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/cda67297.htm">Hyperion CDA 67297</A>: Holst Singers, Stephen Layton (cond)</I></DL>

Title-Type: String Quartet
Title-No: 2
Title-Opus: 148
Title-Dates: 1980

## <DL><DD>Commissioned by Universal Edition, Vienna.<BR>
## In four movements:<BR>
## 1. Moderato (attacca) - 3 min.<BR>
## 2. Agitato (attacca) - 6 min.<BR>
## 3. Mesto (attacca) - 6 min.<BR>
## 4. Moderato - 7 min.<P>
## <I>LP Panton 81 0752: Stamic Quartet<BR>
## CD Arabesque Z 6707: Lark Quartet<BR>
## CD BIS CD 467: Tale Quartet<BR>
## CD Claves CD 50-9504/5 (2 CD-set): (Arrangement by Rachlevsky) Kremlin Chamber Orchestra, Misha Rachlevsky (cond)<BR>
## CD Collins Classics 1450-2: Duke Quartet<BR>
## CD Gramavision GV 79439-2: Arditti Quartet<BR>
## CD Nonesuch 79500-2: Kronos Quartet<BR>
## CD Nonesuch 7559-79504-2 (10 CD-set): Kronos Quartet</I></DL>

Title-RAW: Two Short Pieces
Title-For: organ
Title-Opus: 149
Title-Dates: 1980

## <DL><DD><I>CD Melodiya SUCD 10 00009: O. Yanchenko (organ)<BR>
## CD Melodiya SUCD 10 00066: O. Yanchenko (organ)<BR>
## CD Aurophon AU 31840 <BR>
## CD Precosa-Aulos PRE 66 022 AUL: F. Herz (organ)</I></DL>

Title-RAW: Three Cadenzas to Mozart's Piano Concerto in C major KV 467
Title-Opus: 150
Title-Dates: 1980

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Plane Crew
Title-Opus: 151
Title-Dates: 1980

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Larisa
Title-Opus: 152
Title-Dates: 1980

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Little Tragedies
Title-Opus: 153
Title-Dates: 1980

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Farewell
Title-Opus: 154
Title-Dates: composed with Artyomov, 1980

Title-Type: Symphony
Title-No: 3
Title-Opus: 155
Title-Dates: 1981

## <DL><DD>In four movements:<BR>
## 1. Moderato<BR>
## 2. Allegro<BR>
## 3. Allegro pesante (attacca)<BR>
## 4. Adagio<P>
## <I>LP Melodiya C10 25175: USSR Ministry of Culture SO, Gennadi Rozhdestvensky (cond)<BR>
## CD BIS CD 477: Stockholm PO, Eri Klas (cond)<BR>
## CD Melodiya SUCD 10 00064: USSR Ministry of Culture SO, Gennadi Rozhdestvensky (cond)</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Eugene Onegin
Title-Opus: 156
Title-Dates: 1981

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: What Does Babirussya Need Tusks For?
Title-Opus: 157
Title-Dates: 1981

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: I Am With You Again
Title-Opus: 158
Title-Dates: 1981

Title-Type: Concerto Grosso
Title-No: 2
Title-For: violin, cello and triple symphony orchestra
Title-Opus: 159
Title-Dates: 1981-1982

## <DL><DD>In four movements:<BR>
## 1. Andantino. Allegro - 6 min.<BR>
## 2. Pesante - 9 min.<BR>
## 3. Allegro - 5 min. 30 sec.<BR>
## 4. Andantino - 12 min.<P>
## <I>LP Melodiya A10 00509 005: USSR Ministry of Culture SO, Gennadi Rozhdestvensky (cond)<BR>
## CD BIS CD 567: Malmö SO, Lev Markiz (cond), Oleg Krysa (violin), Torleif Thédéen (cello)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/chan10180.htm">Chandos CHAN 10180</A>: Russian State SO, Valeri Polyansky (cond), Tatiana Grindenko (violin), Alexander Ivashkin (cello)<BR>
## CD Melodiya SUCD 10-00068: USSR Ministry of Culture SO, Gennadi Rozhdestvensky (cond)</I></DL>

Title-Type: Septet
Title-For: flute, two clarinets, violin, viola, cello and harpsichord or organ
Title-Opus: 160
Title-Dates: 1981-1982

## <DL><DD>Introduction. Moderato (attacca)<BR>
## 1. Perpetuum mobile. Allegretto<BR>
## 2. Choral. Moderato<P>
## <I>CD Chandos CHAN 9466: Bolshoi Theatre Orchestra Soloists Ensemble, Valery Polyansky (cond)</I></DL>

Title-RAW: "Course of life" ("Lebenslauf")
Title-For: four metronomes, piano and three percussionists
Title-Opus: 161
Title-Dates: 1982

## <DL><DD>Dedicated to Wilfried Brennecke and John Cage.</DL>

Title-RAW: A Paganini
Title-For: violin solo
Title-Opus: 162
Title-Dates: 1982

## <DL><DD>Andante (one movement).<BR>
## Duration: 11 minutes.<P>
## <I>LP DG 415 484-1: Gidon Kremer (violin)<BR>
## CD ASV CDDCA 877: Mateja Marinkovic (violin)<BR>
## CD BIS CD 697: Oleg Krysa (violin)<BR>
## CD BIS CD 1051: Ilya Gringolts (violin)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/bridge9104.htm">Bridge 9104</A>: Joanna Kurkowicz (violin)<BR>
## CD DG 415 484-2: Gidon Kremer (violin)<BR>
## CD DG 445 520-2: Gidon Kremer (violin)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/phoenix150.htm">Phoenix PHCD 150</A>: Levon Ambartsumian (violin)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/sp22579.htm">Sonora Products SO 22579 CD</A>: Valery Gradow (violin)</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Sturdy Boy
Title-Opus: 163
Title-Dates: 1982

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Autumn
Title-Opus: 164
Title-Dates: 1982

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Pencil and Eraser
Title-Opus: 165
Title-Dates: 1982

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Meteoric Shower/Star Fall
Title-Opus: 166
Title-Dates: 1982

Title-Name: Seid Nüchtern und Wachet
Title-Type-After-Name: cantata
Title-For: soloists (counter-tenor, counter-alto, tenor and bass), mixed chorus and orchestra
Title-Opus: 167
Title-Dates: 1983

## <DL><DD>Text from "The History of D. Johann Faustus".<BR>
## Parts:<BR>
## 1. Folget nun - 3 min.<BR>
## 2. Die vierundzwanzig Jahre - 2 min.<BR> 
## 3. Gehen also miteinander - 2 min.<BR> 
## 4. Meine liebe - 5 min.<BR>
## 5. Ach, mein Herr Fauste - 5 min.<BR>
## 6. Doktor Faustus klagte - 3 min.<BR>
## 7. Es geschah - 5 min.<BR>
## 8. Diese gemeldete Magistri - 3 min.<BR>
## 9. Also endet sich - 4 min.<BR>
## 10. Seid nüchtern und wachet - 3 min.<P>
## <I>CD BIS 437: Malmö SO & Chorus, James DePreist (cond), Inger Blom (mezzo-soprano), Mikael Bellini (alto), Louis Devos (tenor), Ulrik Cold (bass)</I></DL>
## <B>Opus 168: String Quartet no. 3 (1983)</B><BR>
## <DL><DD>Commissioned by Society for New Music, Mannheim.<BR>
## In three movements:<BR>
## 1. Andante - 5 min.<BR>
## 2. Agitato - 7 min.<BR>
## 3. Pesante - 7 min.<P>
## <I>CD Arabesque Z 6707: Lark Quartet<BR>
## CD <A HREF="/ovar/sovrev/schnittke/arco54.htm">Arco Diva UP 0054-2 131</A>: Kapralova Quartet<BR>
## CD BIS CD 467: Tale Quartet<BR>
## CD Etcetera KTC 1124: Mondriaan Quartet<BR>
## CD LDR CD1008: Britten Quartet<BR>
## CD Virgin Classics VC 7 91436-2: Borodin Quartet<BR>
## CD Nonesuch 79500-2: Kronos Quartet</I></DL>

Title-RAW: Cadenza to Mozart's Piano Concerto in C major KV 503 (first movement)
Title-Opus: 169
Title-Dates: 1983

Title-RAW: Two Cadenzas to Mozart's Bassoon Concerto in B flat major KV 191
Title-Opus: 170
Title-Dates: 1983

Title-Name: Sound and Echo (Schall und Hall)
Title-For: trombone and organ
Title-Opus: 171
Title-Dates: 1983

## <DL><DD>Lento (one movement).<BR>
## Duration: 12 minutes.<P>
## <I>CD BIS CD 488: Christian Lindberg (trombone), Gunnar Idenstam (organ)<BR>
## CD Chandos CHAN 9466: Anatoly Skobelev (trombone), Ludmilla Golub (organ)</I></DL>

Title-RAW: "A Streetcar Named Desire (Endstation Sehnsucht)", ballet in two acts by John Neumeier after the play by Tennessee Williams (from Symphony No. 1)
Title-Opus: 172
Title-Dates: 1983

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Leave-Taking
Title-Opus: 173
Title-Dates: 1983

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: A Fairy Tale of Travels
Title-Opus: 174
Title-Dates: 1983

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Darling of the Audience
Title-Opus: 175
Title-Dates: 1983

Title-Type: Symphony
Title-No: 4
Title-For: two vocal soloists, piano, chamber chorus and chamber orchestra
Title-In-Movements: in a single movement
Title-Opus: 176
Title-Dates: 1984

## <DL><DD>Duration: 41 minutes.<P>
## <I>LP Melodiya A10 00271 005: USSR Ministry of Culture Orchestra SO, Gennadi Rozhdestvensky (cond), Viktoria Postnikova (piano)
## CD BIS CD 497: Stockholm Sinfonietta, Uppsala Academic Chamber Choir, Okko Kamu (cond), Mikael Bellini (alto)<BR>
## CD Chandos CHAN 9463: Russian State SO, Russian State Symphonic Cappella, Valery Polyansky (cond), Iaroslav Zdorov (alto), Dmitri Pianov (tenor)<BR>
## CD Melodiya SUCD 10-00065: USSR Ministry of Culture Orchestra SO, Gennadi Rozhdestvensky (cond), Viktoria Postnikova (cond) (Recording: 1986)</I></DL>

Title-Type: Concerto
Title-No: 4
Title-For: violin and orchestra
Title-Opus: 177
Title-Dates: 1984

## <DL><DD>In four movements:<BR>
## 1. Andante (attacca) - 5 min.<BR>
## 2. Vivo (attacca) - 7 min.<BR>
## 3. Adagio (attacca) - 9 min. 30 sec.<BR>
## 4. Lento - 12 min. 30 sec.<P>
## <I>CD BIS CD517: Malmö SO, Eri Klas (cond), Oleg Krysa (violin)<BR>
## CD Teldec 4509-98440-2: Members of Philharmonia Orchestra, Gidon Kremer (violin)</I></DL>

Title-RAW: Transcription of Scott Joplin's Ragtime
Title-For: orchestra
Title-Opus: 178
Title-Dates: 1984

Title-RAW: Transcription of Adolf Jensen's Serenada
Title-For: mezzo-soprano and orchestra
Title-Opus: 179
Title-Dates: 1984

Title-RAW: Transcription of Friedrich Nietsche's Incantation
Title-For: mezzo-soprano and orchestra
Title-Opus: 180
Title-Dates: 1984

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The White Poodle
Title-Opus: 181
Title-Dates: 1984

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Dead Souls
Title-Opus: 182
Title-Dates: 1984

Title-Type: Suite
Title-Related-How: from
Title-Related-Name: Dead Souls
Title-For: orchestra
Title-Opus: 182a

## <DL><DD><I>Live Rec: Royal Concertgebouw Orchestra, Gennadi Rozhdestvensky (cond), Viktoria Postnikova (piano)</I></DL>

Title-Name: Ritual
Title-For: large symphony orchestra
Title-Opus: 183
Title-Dates: 1984-1985

## <DL><DD>In memory of the victims of the Second World War (on occasion of the 40th Anniversary of the liberation of Belgrade).
## Moderato (one movement).
## Duration: 9 minutes.<P>
## <I>CD BIS 437: Malmö SO, Leif Segerstam (cond)</I></DL>

Title-Type: Concerto
Title-For: soprano and mixed chorus
Title-Opus: 184
Title-Dates: 1984-1985

## <DL><DD>On verses from the "Book of Mournful Songs" by Gregory of Narek.<BR>
## Commissioned by Moscow Chamber Choir.<BR>
## Part One - 15 min.<BR>
## Part Two - 7 min. 30 sec.<BR>
## Part Three - 13 min.<BR>
## Part Four - 4 min. 30 sec.<P>
## <I>CD <A HREF="/ovar/sovrev/schnittke/bis1157.htm">BIS 1157</A>: Swedish Radio Choir, Tonu Kaljuste (cond)<BR>
## CD Chandos CHAN 9126: Danish National Radio Choir, Stefan Parkman Cond)<BR>
## CD Chandos CHAN 9332: Russian State Symphonic Cappella, Valery Polyansky (cond)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/cda67297.htm">Hyperion CDA 67297</A>: Holst Singers, Stephen Layton (cond)<BR>
## CD Melodiya SUCD 10 00066: USSR Ministry of Culture Chamber Chorus, Valery Polyansky (cond), E. Dof-Donskaya (soprano)<BR>
## CD Nonesuch 79500-2: Kronos Quartet (arrangement)</I></DL>

Title-RAW: Othello, ballet in two acts by John Neumeier after the tragedy by William Shakespeare
Title-Opus: 185
Title-Dates: 1985

Title-RAW: "Sketches", choreographic phantasy on a theme by Nikolai Gogol, ballet
Title-In-Movements: in one movement
Title-Opus: 186
Title-Dates: 1985

## <DL><DD><I>CD CdM Russian Season RUS 288 155: Bolshoi Theatre Orchestra, Andrey Chistiakov (cond)</I></DL>

Title-RAW: "(K)ein Sommernachtstraum", subtitled
Title-Name: Not after Shakespeare
Title-For: symphony orchestra
Title-Opus: 187
Title-Dates: 1985

## <DL><DD>Duration: 11 minutes.<P>
## <I>CD BIS 437: Malmö SO, Leif Segerstam (cond)<BR>
## CD Chandos CHAN 9722: Russian State SO, Valery Polyansky (cond)<BR>
## CD Pope Music Pm 1007-2: Russian SO, Mark Gorenstein (cond)</I></DL>

Title-Type: Concerto Grosso
Title-No: 3
Title-For: two violins, harpsichord, celesta, piano and fourteen strings
Title-Opus: 188
Title-Dates: 1985

## <DL><DD>In five movements:<BR>
## 1. Allegro - 2 min.<BR>
## 2. Risoluto - 3 min.<BR>
## 3. Pesante - 8 min.<BR>
## 4. Adagio - 8 min.<BR>
## 5. Moderato - 3 min.<P>
## <I>CD Decca 430 698-2: Royal Concertgebouw Orchestra, Riccardo Chailly (cond), R. Brautigam (harpsichord/piano), Viktor Lieberman & Jaap van Zweden (violin)<BR>
## CD London 430 698-2: Royal Concertgebouw Orchestra, Riccardo Chailly (cond), R. Brautigam (harpsichord/piano), Viktor Lieberman & Jaap van Zweden (violin)<BR>
## CD BIS CD 537: Stockholm Chamber Orchestra, Lev Markiz (cond), Patrik Swedrup & Tale Olsson (violin)</I></DL>

Title-Type: Concerto
Title-For: viola and orchestra
Title-Opus: 189
Title-Dates: 1985

## <DL><DD>In three movements:<BR>
## 1. Largo - 5 min.<BR>
## 2. Allegro molto - 12 min.<BR>
## 3. Largo - 17 min.<P>
## <I>LP Melodiya A10 00499 007: USSR Ministry of Culture SO, Gennadi Rozhdestvensky (cond), Yuri Bashmet (viola)<BR>
## CD BIS CD 447: Malmö SO, Lev Markiz (cond), Nobuko Imai (viola)<BR>
## CD EMI CDC 5 55107-2: Jerusalem SO, David Shallon (cond), Tabea Zimmermann (viola)<BR>
## CD Koch Schwann 31523-2: Philharmonia Orchestra, Heinrich Schiff (cond), Isabelle van Keulen (viola)<BR>
## CD Melodiya SUCD 10-00068: USSR Ministry of Culture SO, Gennadi Rozhdestvensky (cond), Yuri Bashmet (viola)<BR>
## CD Regis RRC 1141: USSR Ministry of Culture SO, Gennadi Rozhdestvensky (cond), Yuri Bashmet (viola)<BR>
## CD RCA Victor Red Seal RD 60446: London SO, Mstislav Rostropovich (cond), Yuri Bashmet (viola)<BR>
## CD RCA Victor 74321-24894-2 (2 CD-set): London SO, Mstislav Rostropovich (cond), Yuri Bashmet (viola)<BR>
## CD <A HREF="/ovar/sovrev/kancheli/ecm1471.htm">ECM New Series 1471</A> (437 199-2): Saarbrücken Radio SO, Dennis Russell Davies (cond), Kim Kashkashian (viola)<BR>
## DVD TDK DV-VPOVG: Vienna Philharmonic Orchestra, Valery Gergiev (cond), Yuri Bashmet (viola) (Live recording, 2000)</I></DL>

Title-RAW: Music to an Imagined Play
Title-For: ensemble
Title-Opus: 190
Title-Dates: 1985

## <DL><DD>In three movements:<BR>
## 1. Winter Road<BR>
## 2. Budding Song<BR>
## 3. March<P>
## <I>CD <A HREF="/ovar/sovrev/schnittke/ocd606.htm">Olympia OCD 606</A>: USSR Cinematography SO, Emin Khachaturian (cond)</I></DL>

Title-Type: String Trio
Title-Opus: 191
Title-Dates: 1985

## <DL><DD>Commissioned by the Alban Berg Society in commemoration of the composer's 100th Anniversary.<BR>
## In two movements:<BR>
## 1. Moderato - 12 min. 30 sec.<BR>
## 2. Adagio - 13 min.<P>
## <I>CD ASV CDDCA 868: Mateja Marinkovic (violin), Paul Silverthorne (viola), Timothy Hugh (cello)<BR>
## CD BIS CD 547: Patrik Swedrup (violin), Ingegerd Kierkegaard (viola), Helena Nilsson (cello)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/emi55627.htm">EMI CDC 5 55627 2</A>: Gidon Kremer (violin), Yuri Bashmet (viola), M. Rostropovich (cello)<BR>
## CD Hyperion CDA 66885: Capricorn<BR>
## CD <A HREF="/ovar/sovrev/schnittke/naxos8554728.htm">Naxos 8.554728</A>: Mark Lubotsky & Dimity Hall (violin), Theodore Kuchar & Irini Morozova (viola), Alexander Ivashkin & Julian Smiles(cello), Irina Schnittke (piano)</I></DL>

Title-RAW: Transcription of Alban Berg's Canon, arrangement
Title-For: nine strings
Title-Opus: 192
Title-Dates: 1985

Title-RAW: Transcription of Alban Berg's Canon, arrangement
Title-For: violin and chamberorchestra
Title-Opus: 192a
Title-Dates: 1987

## <DL><DD><I>CD <A HREF="/ovar/sovrev/schnittke/emi55627.htm">EMI CDC 5 55627 2</A>: Moscow Soloists, Gidon Kremer (violin)</I></DL>

Title-Type: Concerto
Title-No: 1
Title-For: cello and orchestra
Title-Opus: 193
Title-Dates: 1985-1986

## <DL><DD>In four movements:<BR>
## 1. Pesante: Moderato - 14 min.<BR>
## 2. Largo - 10 min.<BR>
## 3. Allegro vivace - 4 min.<BR>
## 4. Largo - 12 min.<P>
## <I>CD BIS CD 507: Danish National Radio SO, Leif Segerstam (cond), Torleif Thédéen (cello)<BR>
## CD BIS CD 1507: Danish National Radio SO, Leif Segerstam (cond), Torleif Thédéen (cello)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/bis300507.htm">BIS CD 300507</A>: Danish National Radio SO, Leif Segerstam (cond), Torleif Thédéen (cello)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/chan9852.htm">Chandos CHAN 9852</A>: Russian State Symphony Orchestra, Valery Polyansky (cond), Alexander Ivashkin (cello)<BR>
## CD EMI CDC 7 54443-2: London PO, Kurt Masur (cond), Natalia Gutman (cello)<BR>
## CD Marco Polo 8.223334: Saarbrucken Radio SO, Gerhard Markson (cond), Maria Kliegel (cello)<BR>
## CD Regis RRC 1141: USSR Ministry of Culture SO, Gennadi Rozhdestvensky (cond), Natalia Gutman (cello)<BR>
## CD Sikorski SIK 7-003E: USSR Ministry of Culture SO, Gennadi Rozhdestvensky (cond), Natalia Gutman (cello)</I></DL>

Title-RAW: "Peer Gynt", ballet in three acts by John Neumeier based on Henrik Ibsen's drama
Title-Opus: 194
Title-Dates: 1986

## <DL><DD>Parts:<BR>
## Prologue<BR>
## 1. Into the World - 4 min.<BR>
## <I>Act I: Norway</I><BR>
## 2. Peer and his mother Åse - 2 min.<BR>
## 3. Peer´s Imagination - 4 min.<BR>
## 4. Peer at Ingrid´s wedding celebration - 2 min.<BR>
## 5. Appearance of Solveig and her parents - 4 min.<BR>
## 6. Pas de deux: Solveig-Peer - 4 min.<BR>
## 7. The World of the small-minded Locals - 1 min.<BR>
## 8. In the mountains with Ingrid - 5 min.<BR>
## 9. The Troll-world - 5 min.<BR>
## 10. The Böyg - 3 min. 30 sec.<BR>
## 11. Peer´s Solitude - 1 min. 30 sec.<BR>
## 12. Solveig comes to Peer (pas de deux) - 6 min. 30 sec.<BR>
## 13. The Woman in Green - 2 min. 30 sec.<BR>
## 14. Åse´s Death (pas de deux) - 5 min. 30 sec.<BR>
## <I>Act II: Out in the World - Illusions</I><BR>
## 15. Overture - 3 min. 30 sec.<BR>
## 16. Auditions - 4 min.<BR>
## 17. Rainbow Sextet - 3 min.<BR>
## 18. Peer as Slavedealer - 1 min.<BR>
## 19. Scene and Opening Night Party - 4 min. 30 sec.<BR>
## 20. Emperor of the World - 2 min. 30 sec.<BR>
## 21. Peer´s dance with the whip - 2 min.<BR>
## 22. Solveig´s dance - 2 min. 30 sec.<BR>
## 23. Peer´s mad dance - 2 min. 30 sec.<BR>
## 24. Peer´s coronation - 1 min.<BR>
## 25. Finale - 2 min.<BR>
## <I>Act III: Return</I><BR>
## 26. Mesto - 2 min.<BR>
## 27. Andante - 4 min.<BR>
## 28. Peer´s memories - 2 min.<BR>
## 29. Ingrid´s burial - 3 min.<BR>
## 30. Scene with Solveig - 6 min. 30 sec.<BR>
## 31. Peer surrounded by his aspects - 1 min.<BR>
## 32. Song of the World - 30 sec.<BR>
## 33. The Onion - 3 min.<BR>
## 34. Despair and escape - 40 sec.<BR>
## 35. Deliverance - 2 min.<BR>
## <I>Epilogue:</I><BR>
## 36. Out of the world - 24 min.<BR>
## 37. Appendix - 2 min.<P>
## <I>CD BIS CD 677/8: Stockholm Royal Opera Orchestra, Eri Klas (cond)</I></DL>

Title-Type: Epilogue
Title-Related-How: from
Title-Related-Name: Peer Gynt
Title-For: symphony orchestra and tape (mixed chorus)
Title-Opus: 194a
Title-Dates: 1987

## <DL><DD><I>Live Rec: Oslo PO, Mariss Yansons (cond)</I></DL>

Title-Type: Epilogue
Title-Related-How: from
Title-Related-Name: Peer Gynt
Title-For: cello, piano and tape
Title-Opus: 194b
Title-Dates: 1993

## <DL><DD><I>CD Chandos CHAN 9705: Alexander Ivashkin (cello), Irina Schnittke (piano)</I></DL>

Title-Type: Trio Sonata
Title-For: chamber orchestra
Title-Opus: 195
Title-Dates: 1987

## <DL><DD>Arrangement after the String Trio (1985).<BR>
## 1. Moderato - 18 min.<BR>
## 2. Adagio - 16 min.<P>
## <I>CD BIS CD 537: Stockholm Chamber Orchestra, Lev Markiz (cond)<BR>
## CD Col legno WWE 8CD20041 (9 CD-set)<BR>
## CD ECM New Series 453-512-2: Stuttgart Chamber Orchestra, Dennis Russell Davies (cond)<BR>
## CD RCA Victor Red Seal RD 60446: Moscow Soloists, Yuri Bashmet (cond)</I></DL>

Title-Name: Quasi Una Sonata
Title-For: violin and chamber orchestra
Title-Opus: 196
Title-Dates: 1987

## <DL><DD>Arrangement of Violin Sonata no. 2 (1967).<P>
## <I>CD <A HREF="/ovar/sovrev/schnittke/bis1437.htm">BIS CD 1437</A>: Tapiola Sinfonietta, Ralf Gothoni (cond), Ulf Wallin (violin)<BR>
## CD DG 429 413-2: Chamber Orchestra of Europe, Gidon Kremer (cond & violin), Yuri Smirnov (piano)<BR>
## CD DG 445 520-2: Chamber Orchestra of Europe, Gidon Kremer (cond & violin), Yuri Smirnov (piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/dg471626.htm">DG 471 626-2</A>: Chamber Orchestra of Europe, Gidon Kremer (violin)<BR>
## CD Sony Classical SK 53 271: English Chamber Orchestra, Mstislav Rostropovich (cond), Mark Lubotsky (violin)</I></DL>

Title-Type: Piano Sonata
Title-No: 1
Title-Opus: 197
Title-Dates: 1987-1988

## <DL><DD>Dedicated to Vladimir Feltsman.<BR>
## 1. Lento<BR>
## 2. Allegretto<BR>
## 3. Lento<BR>
## 4. Allegro<P>
## <I>CD <A HREF="/ovar/sovrev/schnittke/bc17292.htm">Berlin Classics 0017292BC</A>: Ragna Schirmer (piano)<BR>
## CD Chandos CHAN 8962: Boris Berman (piano)<BR>
## CD Consonance 81-0009: Vasily Lobanov (piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/mv06.htm">MV Productions SPPS CD06</A>: Svetlana Ponomareva (piano)</I></DL>

Title-Count: Four
Title-Type: Aphorisms
Title-For: chamber orchestra
Title-Opus: 198
Title-Dates: 1988

## <DL><DD>In four movements:<BR>
## 1. Lento<BR>
## 2. Moderato<BR>
## 3. Allegretto<BR>
## 4. Lento<P>
## <I>LP Melodiya: Soloists Ensemble of Bolshoi Theatre Orchestra, A. Lazarev (cond)</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Balcony
Title-Opus: 199
Title-Dates: 1988

Title-RAW: Symphony No. 5 / Concerto Grosso
Title-No: 4
Title-Opus: 200
Title-Dates: 1988

## <DL><DD>In four movements:<BR>
## 1. Allegro - 5 min.<BR>
## 2. Allegretto - 9 min.<BR>
## 3. Lento (attacca). Allegro - 17 min.<BR>
## 4. Lento - 9 min.<P>
## <I>CD BIS CD 427: Gothenburg SO, Neeme Järvi (cond)<BR>
## CD Decca 430 698-2: Royal Concertgebouw Orchestra, Riccardo Chailly (cond)<BR>
## CD London 430 698-2: Royal Concertgebouw Orchestra, Riccardo Chailly (cond)</I></DL>

Title-Type: Concerto
Title-For: piano four hands and chamber orchestra
Title-In-Movements: in a single movement
Title-Opus: 201
Title-Dates: 1988

## <DL><DD>Dedicated to Viktoria Postnikova and Irina Schnittke.<P>
## <I>CD <A HREF="/ovar/sovrev/schnittke/cpo999804.htm">CPO 999 804-2</A>: Radio-Philharmonie Hannover des NDR, Eiji Oue (cond), Genova and Dimitrov Piano Duo<BR>
## CD Erato 2292-45742-2: London Sinfonietta, Gennadi Rozhdestvensky (cond), Irina Schnittke & Victoria Postnikova (piano)<BR>
## CD Revelation RV 10009: Gennadi Rozhdestvensky (cond), Irina Schnittke & Victoria Postnikova (piano)</I></DL>

Title-RAW: Three Verses of Viktor Schnittke
Title-For: tenor and piano
Title-Opus: 202
Title-Dates: 1988

## <DL><DD>1. Wer Gedichte macht, ...<BR>
## 2. Der Geiger<BR>
## 3. Dein Schweigen</DL>

Title-RAW: "Twelve Penitential Psalms", verses of repentance
Title-For: mixed chorus a cappella
Title-Opus: 203
Title-Dates: 1988

## <DL><DD>In twelve movements><P>
## <I>CD Chandos CHAN 9480: Danish National Radio Choir, Stefan Parkman (cond)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/ecm4535132.htm">ECM 453-513-2 (1583)</A>: Swedish Radio Choir, Tonu Kaljuste (cond)</I></DL>

Title-RAW: Piano Quartet in A minor (after Mahler)
Title-Opus: 204
Title-Dates: 1988

## <DL><DD>Dedicated to Oleg Krysa.<BR>
## Quoting a fragment for piano quartet by the 16-year old Gustav Mahler.<BR>
## Allegro (one movement).
## Duration: 6 minutes.<P>
## <I>CD BIS CD 547: Tale Olsson (violin), Ingegerd Kierkegaard (viola), Helena Nilsson (cello), Roland Pöntinen (piano)<BR>
## CD Virgin Classics VC 7 91436-2: Borodin Quartet, Ludmilla Berlinsky (piano)</I></DL>

Title-Name: Sounding Letters (Klingende Buchstaben)
Title-For: solo cello
Title-Opus: 205
Title-Dates: 1988

## <DL><DD>Dedicated to Alexander Ivashkin on the occasion of his 40th birthday.<BR>
## Andantino (one movement)<BR>
## Duration: 4 minutes.<P>
## <I>CD BIS CD 507: Torleif Thédéen (cello)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/bis300507.htm">BIS CD 300507</A>: Torleif Thédéen (cello)<BR>
## CD <A HREF="/ovar/shosrev/cda67534.htm">Hyperion CDA 67534</A>: Alban Gerhardt (cello)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/naxos8554728.htm">Naxos 8.554728</A>: Alexander Ivashkin (cello)<BR>
## CD Ode Manu CDMANU 1480: Alexander Ivashkin (cello)</I></DL>

Title-Type: Monologue
Title-For: viola and chamberorchestra
Title-Opus: 206
Title-Dates: 1989

## <DL><DD>Largo (one movement).<P>
## <I>CD EMI CDC 5 55107-2: Jerusalem SO, David Shallon (cond), Tabea Zimmermann (viola)<BR>
## CD Melodiya SUCD 10 00492: Moscow Soloists, Yuri Bashmet (cond & viola)<BR>
## CD RCA Victor RD 60464: Moscow Soloists, Yuri Bashmet (cond & viola)<BR>
## CD RCA Victor 74321-24894-2: Moscow Soloists, Yuri Bashmet (cond & viola)</I></DL>

Title-RAW: Eröffnungsvers zum Ersten Festspielsonntag
Title-For: mixed chorus and organ
Title-Opus: 207
Title-Dates: 1989

## <DL><DD>Ihr Völker alle, klatscht in die Hände... (from Psalm 47)</DL>

Title-Name: 3 x 7
Title-For: seven instruments
Title-Opus: 208
Title-Dates: 1989

## <DL><DD>For clarinet, horn, trombone, harpsichord, violin, violoncello and double bass.<BR>
## Moderato (one movement)</DL>

Title-Type: String Quartet
Title-No: 4
Title-Opus: 209
Title-Dates: 1989

## <DL><DD>Commissioned by Vienna Concert Hall Society.<BR>
## 1. Lento<BR>
## 2. Allegro<BR>
## 3. Lento<BR>
## 4. Vivace<BR>
## 5. Lento<P>
## <I>CD <A HREF="/ovar/sovrev/schnittke/arco54.htm">Arco Diva UP 0054-2 131</A>: Kapralova Quartet<BR>
## CD EMI CDC 7 54660-2 : Alban Berg Quartet<BR>
## CD EMI CMS 5 65765-2 (4 CD-set): Alban Berg Quartet<BR>
## CD Nonesuch 79500-2: Kronos Quartet<BR>
## CD Nonesuch 7559-79504-2 (10 CD-set): Kronos Quartet</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Visitor of a Museum
Title-Opus: 210
Title-Dates: 1989

Title-Type: Concerto
Title-No: 2
Title-For: cello and orchestra
Title-Opus: 211
Title-Dates: 1990

## <DL><DD>Dedicated to Mstislav Rostropovich.<BR>
## 1. Moderato (attaca) - 4 min.<BR>
## 2. Allegro (attaca) - 10 min.<BR>
## 3. Lento (attaca) - 10 min.<BR>
## 4. Allegretto vivo (attaca) - 5 min.<BR>
## 5. Grave - 16 min.<P>
## <I>CD BIS CD 567: Malmö SO, Lev Markiz (cond), Torleif Thédéen (cello)<BR>
## CD Chandos CHAN 9722: Russian State SO, Valery Polyansky (cond), Alexander Ivashkin (cello)<BR>
## CD Sony Classical CD 48241: London SO, Seiji Ozawa (cond), Mstislav Rostropovich (cello)</I></DL>

Title-RAW: Moz-Art à la Mozart
Title-For: harp and eight flutes
Title-Opus: 212
Title-Dates: 1990

Title-RAW: Madrigal in Memoriam Oleg Kagan
Title-For: violin or solo
Title-Opus: 213
Title-Dates: 1990

## <DL><DD>Lento (one movement).<BR>
## Duration: 10 minutes.<P>
## <I>CD ASV CDDCA 877: Mateja Marinkovic (violin)<BR>
## CD BIS CD 697: Oleg Krysa (violin)</I></DL>

Title-RAW: Madrigal in Memoriam Oleg Kagan
Title-For: cello solo
Title-Opus: 213a
Title-Dates: 1990

## <DL><DD>Lento (one movement)<BR>
## Duration: 12 minutes.<P>
## <I>CD BIS CD 697: Torleif Thédéen (cello)<BR>
## CD <A HREF="/ovar/shosrev/cda67534.htm">Hyperion CDA 67534</A>: Alban Gerhardt (cello)<BR>
## CD Ode Manu CDMANU 1480: Alexander Ivashkin (cello)</I></DL>

Title-Count: Three
Title-Type: Fragments
Title-For: harpsichord
Title-Opus: 214
Title-Dates: 1990

## <DL><DD>1. Andante<BR>
## 2. Vivo<BR>
## 3. Lento</DL>

Title-Count: Five
Title-Type: Aphorisms
Title-For: piano
Title-Opus: 215
Title-Dates: 1990

## <DL><DD>Dedicated to Joseph Brodsky and Alexander Slobodyanik.<BR>
## 1. Moderato assai<BR>
## 2. Allegretto<BR>
## 3. Lento<BR>
## 4. Senza tempo<BR>
## 5. Grave<P>
## <I>CD Chandos CHAN 9704: Boris Berman (piano)<BR>
## CD Ode Manu CDMANU 1480: Tamas Vesmas (piano)<BR>
## CD Thorofon CTH 2459: Peter Martin (piano)</I></DL>

Title-Type: Piano Sonata
Title-No: 2
Title-Opus: 216
Title-Dates: 1990

## <DL><DD>Dedicated to Irina Schnittke.<BR>
## 1. Moderato<BR>
## 2. Lento<BR>
## 3. Allegro moderato<P>
## <I>CD <A HREF="/ovar/sovrev/schnittke/bc17292.htm">Berlin Classics 0017292BC</A>: Ragna Schirmer (piano)<BR>
## CD Chandos CHAN 9704: Boris Berman (piano)<BR>
## CD Sony Classical SK 53 271: Irina Schnittke (piano)</I></DL>

Title-RAW: Cadenzas to Mozart's Piano Concerto in B flat major KV 39
Title-Opus: 217
Title-Dates: 1990

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: Russia: Love For This Country
Title-Opus: 218
Title-Dates: 1990

Title-RAW: Life with an Idiot, opera in 2 acts (4 scenes) by V. Yerofeyev after his likenamed short story
Title-Opus: 219
Title-Dates: 1990-1991

## <DL><DD><I>Sony S2K 52 495: Rotterdam PO, Vocal Ensemble, Mstislav Rostropovich (cond), Dale Duesing (baritone),
## Romain Bischkoff (bass), Teresa Ringholz (soprano), Howard Haskin (tenor), Leonid Zimnenko
## (bass), Robin Leggate (tenor)</I></DL>

Title-Name: Sutartines
Title-For: percussion, organ and string orchestra
Title-Opus: 220
Title-Dates: 1991

Title-RAW: Suite in Old Style
Title-For: chamberorchestra
Title-Opus: 221
Title-Dates: 1991

## <DL><DD>Arrangement of opus 51 by Vladimir Spivakov and Vladimir Milman.<BR>
## 1. Pastorale<BR>
## 2. Ballet<BR>
## 3. Minuet<BR>
## 4. Fugue<BR>
## 5. Pantomime<P>
## <I>LP Melodiya A10 00483 007: USSR Bolshoi Theatre Soloists Ensemble, Gennadi Rozhdestvensky (cond)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/bis1437.htm">BIS CD 1437</A>: Tapiola Sinfonietta, Ralf Gothoni (cond)<BR>
## CD Capriccio 67 016: Moscow Virtuosi, V. Spivakov (cond)<BR>
## CD Consonance 81-0009: Igor Bogulavsky (viola d’amore), Viktor Grislin (vibraphone), Alla Litvienko (harpsichord), Viktor Gabinsky (marimba), Vadim Vasilykov (bells)<BR>
## CD Melodiya SUCD 10 00010: (parts 1 & 2) USSR Bolshoi Theatre Soloists Ensemble, Igor Boguslavsky (viole d'amour)<BR>
## CD RCA Victor Red Seal RD 60370: Moscow Virtuosi, Vladimir Spivakov (cond)<BR>
## CD RCA Victor 74321-24894-2: Moscow Virtuosi, Vladimir Spivakov (cond)<BR>
## CD RCA Victor Artistes Repertoire 82876 502682: Moscow Virtuosi, Vladimir Spivakov (cond)</I></DL>

Title-RAW: Festive Cantus
Title-For: violin, piano, mixed chorus and orchestra
Title-Opus: 222
Title-Dates: 1991

## <DL><DD>Dedicated to Gennadi Rozhdestvensky on the occasion of his 60th birthday.</DL>

Title-Type: Concerto Grosso
Title-No: 5
Title-For: violin, piano and orchestra
Title-Opus: 223
Title-Dates: 1991

## <DL><DD>Commissioned by the Carnegie Hall Corporation for the Cleveland Orchestra on the occasion of the Carnegie Hall Centenary.<BR>
## 1. Allegretto<BR>
## 2. -<BR>
## 3. Allegro vivace<P>
## <I>CD DG 437 091 2: Vienna PO, Christoph von Dohnanyi (cond), Gidon Kremer (violin), Rainer Keuschnig (piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/dg471626.htm">DG 471 626-2</A>: Vienna PO, Christoph von Dohnanyi (cond), Gidon Kremer (violin), Rainer Keuschnig (piano)</I></DL>

Title-RAW: For the 90th Birthday of Alfred Schlee
Title-For: viola solo
Title-Opus: 224
Title-Dates: 1991

Title-Type: Symphony
Title-No: 6
Title-Opus: 225
Title-Dates: 1992

## <DL><DD>Dedicated to Mstislav Rostropovich and The National Symphony Orchestra of Washington.<BR>
## Commissioned by The National Symphony Orchestra of Washington, D. C., and Mstislav Rostropovich.<BR>
## 1. Allegro moderato - 14 min.<BR>
## 2. Presto - 4 min.<BR>
## 3. Adagio (attaca) - 10 min.<BR>
## 4. Allegro vivace - 5 min.<P>
## <I>CD BIS CD 747: BBC National Orchestra of Wales, Tadaaki Otaka (cond)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/chan10180.htm">Chandos CHAN 10180</A>: Russian State SO, Valeri Polyansky (cond)</I></DL>

Title-RAW: Agnus Dei
Title-For: two sopranos, female chorus and chamber orchestra
Title-Opus: 226
Title-Dates: 1992

## <DL><DD>Part of the coope-rative work "Mass for Peace".<BR>
## Lento (one movement)</DL>

Title-Type: Trio
Title-For: violin, cello and piano
Title-Opus: 227
Title-Dates: 1992

## <DL><DD>Arrangement of the String Trio (1985).<BR>
## 1. Moderato - 14 min.<BR>
## 2. Adagio - 13 min.<P>
## <I>CD <A HREF="/ovar/sovrev/schnittke/asv6251.htm">ASV Quicksilva CD QS 6251</A>: Barbican Piano Trio: Gaby Lester (violin), Robert Max (cello), James Kirby (piano)<BR>
## CD BIS CD 697: Oleg Krysa (violin), Torleif Thédéen (cello), Tatiana Tchekina (piano)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/bbm1093.htm">Black Box BBM 1093</A>: Barbican Piano Trio: Gaby Lester (violin), Robert Max (cello), James Kirby (piano)<BR>
## CD Cascavelle VEL 3071: Trio Animae: Tomas Dratva (piano), Jean-Christophe Gawrysiak (violin), Dieter Hilpert (cello)<BR>
## CD Nimbus NI 5572: Vienna Piano Trio (Wolfgang Redik, violin; Marcus Trefny, cello; Stefan Mendl, piano)<BR>
## CD Sony Classical SK 53 271: Mark Lubotsky (violin), Mstislav Rostropovich (cello), Irina Schnittke (piano)</I></DL>

Title-RAW: Musica Nostalgica
Title-For: cello and piano
Title-Opus: 228
Title-Dates: 1992

## <DL><DD><I>CD Chandos CHAN 9705: Alexander Ivashkin (cello), Irina Schnittke (piano)<BR>
## CD <A HREF="/ovar/sovrev/kancheli/qtz2032.htm">Quartz QTZ 2032</A>: Matthew Barley (cello), Stephen De Pledge (piano)</I></DL>

Title-Type: Piano Sonata
Title-No: 3
Title-Opus: 229
Title-Dates: 1992

## <DL><DD>1. Lento<BR>
## 2. Allegro<BR>
## 3. Largo<BR>
## 4. Allegro<P>
## <I>CD <A HREF="/ovar/sovrev/schnittke/bc17292.htm">Berlin Classics 0017292BC</A>: Ragna Schirmer (piano)<BR>
## CD Chandos CHAN 9704: Boris Berman (piano)</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Last Days of St. Petersburg
Title-Opus: 230
Title-Dates: 1992

## <DL><DD><I>CD <A HREF="/ovar/sovrev/schnittke/cpo999796.htm">CPO 999 796-2</A>: Radio SO Berlin, Frank Strobel (cond)</I></DL>

Title-RAW: Hommage to Dr. Zhivago, musical allegory
Title-Related-How: on motives of B. Pasternak's novel
Title-Related-Name: Doctor Zhivago
Title-Opus: 231
Title-Dates: 1993

Title-RAW: "Gesualdo", opera in seven acts, a prologue and an epilogue by Richard Bletschacher
Title-Opus: 232
Title-Dates: 1993

Title-RAW: Hommage to Grieg
Title-For: orchestra
Title-Opus: 233
Title-Dates: 1993

## <DL><DD>Arrangement of a fragment from the ballet "Peer Gynt" for orchestra.<BR>
## Adagio (one movement)><P>
## <I>CD <A HREF="/ovar/sovrev/schnittke/cpo999804.htm">CPO 999 804-2</A>: Radio-Philharmonie Hannover des NDR, Eiji Oue (cond)</I></DL>

Title-Type: Symphony
Title-No: 7
Title-Opus: 234
Title-Dates: 1993

## <DL><DD>Dedicated to Kurt Masur.<BR>
## Commissioned by the New York Philharmonic Orchestra.<BR>
## 1. Andante (attaca) - 5 min.<BR>
## 2. Largo - 2 min. 30 sec.<BR>
## 3. Allegro - 14 min.<P>
## <I>CD BIS CD 747: BBC National Orchestra of Wales, Tadaaki Otaka (cond)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/chan9852.htm">Chandos CHAN 9852</A>: Russian State Symphony Orchestra, Valery Polyansky (cond)<BR></I></DL>

Title-Type: Concerto Grosso
Title-No: 6
Title-For: piano, violin and string orchestra
Title-Opus: 235
Title-Dates: 1993

## <DL><DD><I>Antes Edition BM-CD31.9187: Bulgarian Orpheus Chamber Orchestra, Raitscho Christov (cond), Falko Steinbach (piano), Yosif Raduinov (violin)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/bis1437.htm">BIS CD 1437</A>: Tapiola Sinfonietta, Ralf Gothoni (cond & piano), Ulf Wallin (violin)<BR>
## CD Chandos CHAN 9359: Stockholm PO, Gennadi Rozhdestvensky (cond), Sasha Rozhdestvensky (violin), Viktoria Postnikova (piano)<BR>
## CD Nimbus NI 5582: English SO, William Boughton (cond), Daniel Hope (violin), Simon Mulligan (piano)</I></DL>

Title-RAW: "Mother" for mezzo-soprano and piano after verses by Else Lasker-Schüler
Title-Opus: 236
Title-Dates: 1993

## <DL><DD>Dedicated to Ulrich Eckhardt on occasion of his 60th birthday.<BR>
## Lento (one movement)</DL>

Title-RAW: Improvisation
Title-For: cello solo
Title-Opus: 237
Title-Dates: 1993

## <DL><DD>Commissioned by the 'Acanthes' contest, October 1994.<BR>
## Dedicated to Mstislav Rostropovich.<BR>
## Andante poco rubato (one movement)<P>
## <I>CD Ode Manu CDMANU 1480: Alexander Ivashkin (cello)<BR>
## CD Thorofon CTH 2459: Sonja Schröder (cello)</I></DL>

Title-Type: Music
Title-Related-How: to the Film
Title-Related-Name: The Master and Margarita
Title-Opus: 238
Title-Dates: 1993

## <DL><DD><I>CD <A HREF="/ovar/sovrev/schnittke/cpo999796.htm">CPO 999 796-2</A>: Radio SO Berlin, Frank Strobel (cond)</I></DL>

Title-RAW: "The History of Dr. Johann Faustus", opera in three acts, a prologue and an epilogue by Jörg Morgener and Alfred Schnittke
Title-Opus: 239
Title-Dates: 1994

## <DL><DD>Based on the likenamed book published by Johann Spies in 1587<P>
## <I>CD RCA Victor Red Seal 09026-68413-2: Hamburg State Opera Chorus and Orchestra, Gerd Albrecht (cond), 
## Jurgen Freier (baritone), Eberhard Lorenz (tenor), Arno Raunig (alto), 
## Hanna Schwarz (mezzo-soprano), Eberhard Buchner (tenor), Jonathan Barreto-Ramos (tenor), Christoph Johannes Wendel (baritone), Jurgen Fersch (bass)</I></DL>

Title-Type: Symphonic Prelude
Title-Opus: 240
Title-Dates: 1994

## <DL><DD>Commissioned by the Hamburg Philharmonic State Orchestra.<BR>
## Andante (one movement).<BR>
## Duration: 17 min. 30 sec.<P>
## <I>CD <A HREF="/ovar/sovrev/schnittke/bis1217.htm">BIS CD 1217</A>: Norrkoping Symphony Orchestra, Lü Jia (cond)</I></DL>

Title-Type: Symphony
Title-No: 8
Title-Opus: 241
Title-Dates: 1994

## <DL><DD>Dedicated to Gennadi Rozhdestvensky and the Royal Stockholm Philharmonic Orchestra.<BR>
## Commissioned by Stockholm Concert Hall Foundation.<BR>
## 1. Moderato - 8 min. 30 sec.<BR>
## 2. Allegro moderato - 4 min. 30 sec.<BR>
## 3. Lento - 16 min.<BR>
## 4. Allegro moderato - 5 min.<BR>
## 5. Lento - 2 min.<P>
## <I>CD <A HREF="/ovar/sovrev/schnittke/bis1217.htm">BIS CD 1217</A>: Norrkoping Symphony Orchestra, Lü Jia (cond)<BR>
## CD Chandos CHAN 9359: Stockholm PO, Gennadi Rozhdestvensky (cond)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/chan9885.htm">Chandos CHAN 9885</A>: Russian State SO, Valeri Polyansky (cond)</I></DL>

Title-Name: For Liverpool
Title-For: orchestra
Title-Opus: 242
Title-Dates: 1994

## <DL><DD>Commissioned by The Royal Liverpool Philharmonic Society with funds provided by the Art Council of England.<BR>
## Duration: 12 min. 30 sec.<P>
## <I>CD <A HREF="/ovar/sovrev/schnittke/bis1217.htm">BIS CD 1217</A>: Norrkoping Symphony Orchestra, Lü Jia (cond)</I></DL>

Title-Type: Triple concerto
Title-For: violin, viola, cello and string orchestra
Title-Name: Concerto for Three
Title-Opus: 243
Title-Dates: 1994

## <DL><DD>1. Moderato - 6 min.<BR>
## 2. Larghetto - 4 min. 30 sec.<BR>
## 3. Largo - 4 min. 30 sec.<BR>
## 4. Attaca - Minuet - 5 min.<P>
## <I>CD BIS CD 1379/80 (2 CD-set): Toho Gakuen Orchestra, Koichiro Harada (cond), Yasushi Toyoshima (violin), Noboru Kamimura (cello), Nobuko Imai (viola)<BR>
## CD <A HREF="/ovar/sovrev/schnittke/emi55627.htm">EMI CDC 5 55627 2</A>: Moscow Soloists, Gidon Kremer (violin), Yuri Bashmet (viola), Mstislav Rostropovich (cello)<BR>
## CD Quartz QTZ 2052: West Kazakhstan Philharmonic Orchestra, Mikel Toms (cond), Roman Mints (violin), Maxim Rysanov (viola), Kristine Blaumane (cello)</I></DL>

Title-RAW: Five Fragments to Pictures of Hieronymus Bosch
Title-For: tenor, violin, trombone, harpsichord, timpani and string orchestra
Title-Opus: 244
Title-Dates: 1994

## <DL><DD>On texts by Aeshylus.<BR>
## Dedicated to Vladimir Spivakov.<BR>
## 1. Lento<BR>
## 2. Moderato<BR>
## 3. Andantino<BR>
## 4. Agitato<BR>
## 5. Senza tempo<P>
## <I>CD Capriccio 67 016: Moscow Virtuosi, V. Spivakov (cond)</I></DL>

Title-Name: Lux Aeterna
Title-For: mixed chorus and orchestra
Title-Opus: 245
Title-Dates: 1994

## <DL><DD>Orchestrated by Gennadi Rozhdestvensky.<BR>
## Commissioned by the International Bach Academy Stuttgart as part of the cooperative work 'Requiem of Reconciliation' for Europãisches Musikfest Stuttgart.<BR>
## Andante (one movement)</DL>

Title-Type: Sonata
Title-No: 2
Title-For: cello and piano
Title-Opus: 246
Title-Dates: 1994

## <DL><DD>Dedicated to Mstislav Rostropovich.<BR>
## 1. Senza tempo<BR>
## 2. Allegro<BR>
## 3. Largo<BR>
## 4. Allegro<BR>
## 5. Lento<P>
## <I>CD <A HREF="/ovar/sovrev/schnittke/bbm11032.htm">Black Box BBM 1032</A>: Raphael Wallfisch (cello), John York (piano)<BR>
## CD Chandos CHAN 9705: Alexander Ivashkin (cello), Irina Schnittke (piano)<BR>
## CD <A HREF="/ovar/sovrev/kabalevsky/emi5720162.htm">EMI CZS 572016-2</A> (13 CD-set): Mstislav Rostropovich (cello), Aza Amintayeva (piano)<BR>
## CD Thorofon CTH 2459: Sonja Schröder (cello), Peter Martin (piano)</I></DL>

Title-Type: Quartet
Title-For: four percussionists
Title-Opus: 247
Title-Dates: 1994

## <DL><DD>Andante (one movement)</DL>

Title-Type: Sonata
Title-No: 3
Title-For: violin and piano
Title-Opus: 248
Title-Dates: 1994

## <DL><DD>Dedicated to Mark Lubotsky.<BR>
## 1. Andante<BR>
## 2. Allegro (molto)<BR>
## 3. Adagio<BR>
## 4. Senza tempo<P>
## <I>CD <A HREF="/ovar/sovrev/schnittke/ni5631.htm">Nimbus NI 5631</A>: Daniel Hope (violin), Simon Mulligan (piano)<BR>
## CD Ondine ODE 893-2: Mark Lubotsky (violin), Irina Schnittke (piano)<BR>
## CD Stradivarius STR 33675: Francesco D'Orazio (violin), Giampaolo Nuti (piano)</I></DL>

Title-Type: Minuet
Title-For: violin, viola and cello
Title-Opus: 249
Title-Dates: 1994

## <DL><DD>Originally composed as an encore for the first performance of the Concerto for violin, viola and cello.<BR>
## Dedicated to Gidon Kremer, Yuri Bashmet and Mstislav Rostropovich.<P>
## <I>CD <A HREF="/ovar/sovrev/schnittke/emi55627.htm">EMI CDC 5 55627 2</A>: Gidon Kremer (violin), Yuri Bashmet (viola), Mstislav Rostropovich (cello)</I></DL>

Title-Type: Sonatina
Title-For: piano four hands
Title-Opus: 250
Title-Dates: 1995

## <DL><DD>Allegro moderato (one movement)</DL>

Title-Type: Concerto
Title-For: viola and small orchestra
Title-Opus: 251
Title-Dates: 1997

Title-Type: Variations
Title-For: string quartet
Title-Opus: 252
Title-Dates: 1997

Title-Type: Symphony
Title-No: 9
Title-Opus: 253
Title-Dates: 1996-1998

## <DL><DD>Unfinished.</DL>
## <hr width=40% align=center size=3><P>
