ifeq ($(BOARD_HAVE_BLUETOOTH),true)
ifeq ($(BOARD_USE_AR3K_BLUETOOTH),true)
LOCAL_PATH := $(call my-dir)
AR_FW_PATH := 30101
INSTALL_PATH := $(TARGET_OUT)/lib/firmware/ar3k/$(AR_FW_PATH)

include $(CLEAR_VARS)
LOCAL_MODULE := ar3kbdaddr.pst
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(INSTALL_PATH)
LOCAL_SRC_FILES := $(AR_FW_PATH)/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := PS_ASIC.pst
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(INSTALL_PATH)
LOCAL_SRC_FILES := $(AR_FW_PATH)/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := RamPatch.txt
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(INSTALL_PATH)
LOCAL_SRC_FILES := $(AR_FW_PATH)/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

endif
endif
